### PR TITLE
Execution reference on the artifact view what execution produced the artifacts

### PR DESCRIPTION
**Pull request by pnaik1**
https://issues.redhat.com/browse/RHOAIENG-14415

## Description
added the execution reference in the artifact detail page that it came from and if it was cached then show the root execution

Screenshot 2024-11-20 at 3 10 13 PM

## How Has This Been Tested?

1. Run a pipeline which contains artifacts
2. Go to Artifact Page-> click on the artifactName
3. check if the Reference section is present 
4. Check if the execution link redirects to execution page
5. Check execution link is a root execution link if its cached

## Test Impact
Added cypress test cases

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`
cc @yannnz

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
@pnaik1 this looks good. however i think we should also add the reference to the pipeline run in the list of references if possible. PMs request was looking to get back to run directly from the artifact

> I can go from the run view to an artifact, but I can’t go from an artifact list to which run it was produced by.

**Review by Gkrumbach07 — COMMENTED** [review]
Code and functionality looks good otherwise

**Comment by pnaik1** [comment]
@Gkrumbach07  `PMs request was looking to get back to run directly from the artifact`
Does this mean to list all the pipeline runs (even runs from cached execution) connected to the artifact or just the root pipeline run which created it
Ex:
```
Execution-1 -> run-id-1-> artifact-1
Execution-2(cached)->run-id-2-> artifact-1
```

the artifact details page should look something like this???

```
Pipeline run.      run-id-1
                   run-id-2
```
or just original/root runs

`Pipeline run.        run-id-1`

**Comment by yannnz** [comment]
For the cached one, would it be something like this in the screenshot? Under the Reference section, list the Run and execution cached this artifact, then list the original run and execution created this artifact.  `Root` might sounds more accurate than `Original `, but we name it as`Original ` execution under the Execution detail page. 

Screenshot 2024-11-15 at 21 37 45

**Comment by yannnz** [comment]
I left comments in the Slack: https://redhat-internal.slack.com/archives/C07C0FNHVPT/p1731912641438389

**Comment by pnaik1** [comment]
@yannnz @Gkrumbach07 I have updated the screenshot?? I have given the name `Original run` and `Original execution` since this are the execution/ runs which actually produced the artifact, Can you have a look at it, if thats fine

**Pull request merged**
