### PR TITLE
test: Storage Classes e2e cypress tests

### PR DESCRIPTION
**Pull request by FedeAlonso**
https://issues.redhat.com/browse/RHOAIENG-11613

## Description
e2e Cypress test cases for Storage Class Feature

Settings->Storage class view:
- A non admin user can not acccess to Settings -> Storage classes view
- The Default label is shown in the grid
- An admin user can enable a disabled Storage Class
- An admin user can disable an enabled Storage Class
- An admin user can set an enabled Storage Class as the default one
- An admin user can edit an Storage Class

Cluster Storage view from the Cluster Storage DSP tab:
- Regular user can create a cluster storage using a new storage class
- A Cluster Storage with a disabled SC shows the deprecated warning
- If all SC are disabled except one, the SC dropdown should be disabled

## How Has This Been Tested?
As there were some UI changes, the tests ran against the local UI and a 2.14 cluster as the backend

image

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [x] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by manosnoam — COMMENTED** [review]
Thank you Fede!
Can you share job results from Jenkins ?

**Comment by FedeAlonso** [comment]
> Thank you Fede! Can you share job results from Jenkins ?

@manosnoam As this PR has UI modifications, I'm not running this in jenkins. 
The results:

Cluster Storage:
Screenshot from 2024-10-07 13-20-30

Storage Class:
Screenshot from 2024-10-07 13-24-26
(The one that's failing is because when running the UI locally it uses the token from the oc login instead of performing a login. As the OC login is done with an admin user in order to provision, teardown, and have access to admin views, and the test which fails is testing that a non admin user has no access to the storage classes view which is one of those only admin views)

**Comment by FedeAlonso** [comment]
@manosnoam here you have the result of the failing test when executed against a live cluster :
image

**Comment by FedeAlonso** [comment]
I've deleted some tests as they were already done for the mockend environment.
Results:
image

**Review by manosnoam — APPROVED** [review]

**Pull request merged**
