### PR TITLE
made env upload category more specific

### PR DESCRIPTION
**Pull request by Gkrumbach07**
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1206

## Description

When secret upload was added, the category for the env upload was "upload" for both secrets and config maps. B/c the upload for secret was checked first, uploaded envs would always be created as secrets.

## How Has This Been Tested?

create a workbench with an uploaded config map and make sure it is created as a config map and not a secret

## Test Impact

no impact

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)
no ux changes

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

Tested and its working fine:
Screenshot 2023-05-10 at 18 33 04

Screenshot 2023-05-10 at 18 32 53

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
I can't upload secrets 🤔 

Was this broken by your code? -- Yup. Because we didn't implement the reference to Secret UPLOAD when we did it originally -- https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/projects/screens/spawner/spawnerUtils.ts#L323

**Review by andrewballantyne — APPROVED** [review]

**Review by lucferbux — APPROVED** [review]
/lgtm

**Pull request merged**
