### PR TITLE
UX updates for content and behavior in event log modal for a starting workbench

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
JIRA: https://issues.redhat.com/browse/RHOAIENG-14737

## Description

Update several places:
1. Update the waiting message from "Waiting for notebook to start..." to "Waiting for workbench to start..." and the popover title from "Notebook status" to "Workbench status"

Screenshot 2024-10-29 at 5 22 52 PM

2. Update the event modal title from "Starting server" to "Starting workbench" and Update the cancel button text from "Cancel" to "Stop workbench"

Screenshot 2024-10-29 at 5 22 44 PM

3. When stop workbench from the event modal, it will also prompt a confirmation modal now

Screenshot 2024-10-29 at 5 25 09 PM

## How Has This Been Tested?

1. Create a workbench
2. Start and stop it, check the event modal
3. Make sure all the content and behavior are as described

## Test Impact

Updated some cypress tests to adapt to the change

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
FYI, data test IDs were updated as a result of this PR
@manosnoam

**Comment by pnaik1** [comment]
Tested in the live cluster
all the content and behaviors works as expected
Screenshot 2024-10-30 at 3 47 45 PM
Screenshot 2024-10-30 at 3 44 49 PM
Screenshot 2024-10-30 at 3 47 12 PM

Just a small comment:
https://github.com/opendatahub-io/odh-dashboard/pull/3401/files#diff-ed8131a3c29c559bbe0d910b599e583b4589517174c05d0bc13a7d48a014dec8L49-R58 this 
We do have another location to change, but this isn't displayed in the UI because the modal only opens when the workbench is starting. Can we consider removing this piece of code?

**Comment by jgiardino** [comment]
Thanks for making these updates, @DaoDaoNoCode! These look good to me.

**Comment by pnaik1** [comment]
@DaoDaoNoCode thanks for the changes
/lgtm

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm

tested and working as expected

**Pull request merged**
