### PR TITLE
Show App Launcher Icons

### PR DESCRIPTION
**Pull request by andrewballantyne**
https://issues.redhat.com/browse/RHOAIENG-12283

## Description

Show app launcher icons.

Also hide ODH ConsoleLink when inside the Dashboard.

### Before
Screenshot 2024-09-04 at 8 36 34 AM

### After
image

## How Has This Been Tested?

Adding a ConsoleLink for the `ApplicationMenu` location with an icon and seeing if the new console link renders with an icon

## Test Impact

Added test for making sure ODH doesn't appear (based on the consolelink setup in manifests -- could be brittle)

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

cc @kywalker-rh

### CODE REVIEW

**Comment by pnaik1** [comment]
Verified locally 
The odh Link doesnt show up when when inside the Dashboard.
The custom consoleLink shows the app Launcher icons
/lgtm
Screenshot 2024-09-04 at 7 49 26 PM

**Comment by andrewballantyne** [comment]
/hold 

Need to add a test to verify the data

**Comment by andrewballantyne** [comment]
/unhold

tests added

**Review by DaoDaoNoCode — APPROVED** [review]
Tested, works well.
/lgtm

Screenshot 2024-09-04 at 1 02 50 PM

**Pull request merged**
