### PR TITLE
Cypress e2e Verify That Administrators Can Access "Cluster Settings"

### PR DESCRIPTION
**Pull request by antowaddle**
https://issues.redhat.com/browse/RHOAIENG-12646

## Description
Migration of the below Robot test to Cypress

ODS-1216

Note - as part of the test I also added a check to ensure that non-admins couldn't access Cluster Settings which is documented as a Robot test
ODS-1217

https://opendatascience-jenkins-csb-rhods.apps.ocp-c1.prod.psi.redhat.com/job/rhoai/job/2.13/job/selfmanaged/job/cli/job/aws/job/rhoai-smoke/1/robot/report/log.html#s1-s4-s2-s4-s1-t3 

## How Has This Been Tested?

- An oc login should be performed in the cluster before running the test
- test-variables.yml should be configured properly
- Export the path to the test-variables.yml: $ export CY_TEST_CONFIG=<path_to>/test-variables.yml
- This was also tested by changing 'odh-dashboard-config' settings and validating the inverse conditions i.e. when settings should not display etc. 

image

Tested with >= odh-operator-bundle-container-v2.16.0-16 on a PSI Cluster and also ran the test against ODH-Nightly. 

## How to run
After exporting the test-variables.yml we have 2 different ways:

Using the UI
Go to odh-dashboard/frontend/src/tests/cypress and run the command npx cypress open . This will open the Cypress UI where testAdminClusterSettings.cy.ts can be run.

Headless
Go to odh-dashboard/frontend/src/tests/cypress and run the command _'npx cypress run --spec "cypress/tests/e2e/settings/clusterSettings/testAdminClusterSettings.cy.ts" --browser chrome'_

## Test Impact
This is already a test.

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by antowaddle** [comment]
As discussed just now on our weekly Cypress call, I'll enhance this test to verify the values on the backend and then check the UI.

**Comment by manosnoam** [comment]
> As discussed just now on our weekly Cypress call, I'll enhance this test to verify the values on the backend and then check the UI.

Thanks @antowaddle please see this Epic which shows the general tests we need to verify cluster configs in UI:
https://issues.redhat.com/browse/RHOAIENG-6876

The Dashboard config spec can be retrieved via:
`oc get OdhDashboardConfig -A -o json | jq '.items[].spec'`

**Comment by andrewballantyne** [comment]
FYI @antowaddle... if you put `[WIP]` at the start of your PR title, it marks it "Work In Progress" and the label prevents the bot from merging it even if it's approved.

**Review by manosnoam — COMMENTED** [review]
/lgtm 
Thanks for adding the backend verification of cluster config and notebook controller.

**Comment by FedeAlonso** [comment]
/lgtm 
image

**Pull request merged**
