### PR TITLE
tooltip on pipeline screen impede clicking of the slider right above

### PR DESCRIPTION
**Pull request by pnaik1**
Closes: #1586 

## Description
Removed the tooltip
 

[Screencast from 2023-09-06 19-54-12.webm](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/961c95a9-4996-4b4a-8b09-e9a1566710b4)

## How Has This Been Tested?
1. Create some scheduled runs
2. Go to Run page and in the Scheduled tab check for the status column

## Test Impact
No test coverage

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
cc @kywalker-rh

**Review by lucferbux — COMMENTED** [review]
/lgtm
Not approving until @kywalker-rh ack this, but based in previous conversations this seems to be the solution.

**Review by manaswinidas — APPROVED** [review]
/lgtm 

Tested. Works fine for me.

**Comment by manaswinidas** [comment]
@pnaik1 Can you please update the GIF in the PR description, it doesn't show the pointer. Can you please record one with the mouse pointer and hover on the button(needn't click on it)?

**Comment by pnaik1** [comment]
Updated the GIF , thanks @manaswinidas

**Review by DaoDaoNoCode — APPROVED** [review]
/lgtm

**Comment by kywalker-rh** [comment]
Acknowledged... this matches the earlier decision.

**Pull request merged**
