### PR TITLE
Add culler timeout settings feature

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Screen Shot 2022-03-09 at 8 16 34 PM
The config map `jupyterhub-cfg` will be changed when users change the culler timeout settings.

### CODE REVIEW

**Review by dlabaj — APPROVED** [review]

**Comment by dlabaj** [comment]
LGTM

**Comment by DaoDaoNoCode** [comment]
@crobby Could you also review it when you get a chance?

**Review by dlabaj — APPROVED** [review]
LGTM

**Pull request merged**
