### PR TITLE
Hold the last activity time of the Notebook until spawn modal closes

### PR DESCRIPTION
**Pull request by andrewballantyne**
Resolves: #636 

## Description

Holds onto the Date object of the last-activity for as long as the modal is open -- even if the Notebook stops. 

## How Has This Been Tested?

This is interesting -- no clean way to reproduce this. @cfchase found that sometimes K8s would send an event that said the pod was being deleted due to scheduling issues -- this somehow triggered the Notebook to get the stop annotation. Which naturally caused a loss of last-activity and the modal log cleared.

This will prevent that, but it's hard to reproduce.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by cfchase — APPROVED** [review]
/lgtm

**Comment by andrewballantyne** [comment]
Had debug code... just removed it

**Review by dlabaj — APPROVED** [review]
/lgtm

**Review by cfchase — APPROVED** [review]
/lgtm

tested by manually messing with my notebook resource during spawn to cause a failure.

**Pull request merged**
