### PR TITLE
Cleanup display names on projects

### PR DESCRIPTION
**Pull request by andrewballantyne**
Startup cleanup script for #744 

Follow up on #763

### CODE REVIEW

**Comment by andrewballantyne** [comment]
/hold

Talked with Chris, he suggested a quick writing of a configmap that will prevent this flow from running more than once.

**Comment by andrewballantyne** [comment]
/unhold

@DaoDaoNoCode Please do another review, added a configmap setting to help on performance.

**Review by DaoDaoNoCode — APPROVED** [review]
lgtm

**Review by lucferbux — APPROVED** [review]
/lgtm

**Pull request merged**
