### PR TITLE
Remove last remaining traces of modelMetricsNamespace flag

### PR DESCRIPTION
**Pull request by alexcreasy**
## Description

Removes a few orphaned references to the removed `modelMetricsNamespace` flag.

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]

**Comment by andrewballantyne** [comment]
Oh, you broke tests... no approval for you 🙂

**Comment by lucferbux** [comment]
@alexcreasy should we merge this? it's been open for a couple of months

**Comment by andrewballantyne** [comment]
Okay, GitHub allowed a rebase -- the test info was lost and seemed to not want me to retest it -- so I figured this way we can try to merge this if the tests pass.

**Review by andrewballantyne — APPROVED** [review]
Seems to not be on Alex's radar -- going to merge as-is, it's minor cleanup.

**Pull request merged**
