### PR TITLE
Add downstream changes

### PR DESCRIPTION
**Pull request by VaishnaviHire**
This PR is created to list down changes that can be moved to `opendatahub-io` org.

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
I'd like to add the changes to how we fetch the application definitions and documentation from https://github.com/red-hat-data-services/odh-dashboard/pull/79

**Comment by crobby** [comment]
Are we good to go on this one yet?  @jeff-phillips-18 @VaishnaviHire

**Comment by VaishnaviHire** [comment]
https://github.com/opendatahub-io/odh-dashboard/pull/48#issuecomment-852340487

Not sure if we first want to include changes from this PR - https://github.com/red-hat-data-services/odh-dashboard/pull/88 ?

**Comment by jeff-phillips-18** [comment]
I think maybe we are better of to go forward with this PR and add changes for https://github.com/red-hat-data-services/odh-dashboard/pull/88 later. @crobby @cfchase thoughts?

**Comment by crobby** [comment]
> I think maybe we are better of to go forward with this PR and add changes for [red-hat-data-services#88](https://github.com/red-hat-data-services/odh-dashboard/pull/88) later. @crobby @cfchase thoughts?

I'm happy with that approach.

**Review by cfchase — APPROVED** [review]

**Comment by cfchase** [comment]
> I think maybe we are better of to go forward with this PR and add changes for [red-hat-data-services#88](https://github.com/red-hat-data-services/odh-dashboard/pull/88) later. @crobby @cfchase thoughts?

Sounds good to me.

**Review by crobby — APPROVED** [review]

**Pull request merged**
