### PR TITLE
update anaconda image

### PR DESCRIPTION
**Pull request by trujillm**
The moment you have been waiting for is here! An update to the anaconda image

### CODE REVIEW

**Comment by andrewballantyne** [comment]
Please rebase your branch and avoid merges... it makes a cleaner history

**Comment by trujillm** [comment]
> Please rebase your branch and avoid merges... it makes a cleaner history

✅

**Review by andrewballantyne — APPROVED** [review]
Already reviewed downstream https://github.com/red-hat-data-services/odh-dashboard/pull/324 by Sean.

Approving.

FYI @Xaenalt

**Pull request merged**
