### PR TITLE
[RHOAIENG-11333] Modify status labels for runs and executions

### PR DESCRIPTION
**Pull request by jpuzz0**
https://issues.redhat.com/browse/RHOAIENG-11333

## Description
Updated icons/labels for statuses based on this figma referenced in the JIRA issue: https://www.figma.com/design/Beh8E4dQQ5hq0Kzd9qLaCZ/Pipelines-v2-enhancements?node-id=582-15436

## How Has This Been Tested?
Verify all pages referenced in the [figma](https://www.figma.com/design/Beh8E4dQQ5hq0Kzd9qLaCZ/Pipelines-v2-enhancements?node-id=582-15436) (or [this doc](https://docs.google.com/document/d/1psldOcTvZskdnuedg7CI05UiA-l7mQWfSPMCdRI6vAA/edit#heading=h.l5i04lmgilak), which is just another way of consuming the same information) match.

## Test Impact
Had to update some tests to account for icon changes. Otherwise, these are non-functional changes so shouldn't effect cypress tests.

## Request review criteria:
Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
Screenshot 2024-10-17 at 3 34 12 PM

group nodes need their loading icon updated
the canceled icon is not the new one

**Comment by jpuzz0** [comment]
> group nodes need their loading icon updated the canceled icon is not the new one for group nodes
> 
> seems like group nodes were missed in general
@Gkrumbach07 I can update the "Running" statuses to show the expected light blue/in progress icon, however the Canceled state's icon is not overridable after discussing with @jeff-phillips-18. I've opened an issue to Topology for this to be addressed: https://github.com/patternfly/react-topology/issues/240.

How would you like to proceed with this issue in the meantime?

**Comment by jpuzz0** [comment]
> > group nodes need their loading icon updated the canceled icon is not the new one for group nodes
> > seems like group nodes were missed in general
> 
> @Gkrumbach07 I can update the "Running" statuses to show the expected light blue/in progress icon, however the Canceled state's icon is not overridable after discussing with @jeff-phillips-18. I've opened an issue to Topology for this to be addressed: [patternfly/react-topology#240](https://github.com/patternfly/react-topology/issues/240).
> 
> How would you like to proceed with this issue in the meantime?

I've added a comment and a new follow-up story to address the custom icon for Canceled status group nodes. Our team's jira issue is here; https://issues.redhat.com/browse/RHOAIENG-14822 and the PF issue is here; https://github.com/patternfly/react-topology/issues/240.

**Comment by DaoDaoNoCode** [comment]
All lgtm, just have one request that's not related to this PR but I hope to see if it's possible to make changes here.

In https://github.com/opendatahub-io/odh-dashboard/pull/3140, I changed the icon for the artifact nodes based on the metrics type. However, looks like I only changed the icon when it's not hovered. If the node is hovered, the icon will be incorrect.

e.g. In the following 2 screenshot, the icon should be both monitoring icon, however, the second one is a list icon
Screenshot 2024-10-21 at 5 09 01 PM
Screenshot 2024-10-21 at 5 09 20 PM

The reason is I only updated https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx#L89, but didn't update https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx#L132 and https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx#L155 to use the `isMetricsArtifactType` function, which causes the inconsistency.

Could you update that in this PR because it's also about the icon/status? Thanks!

**Comment by jpuzz0** [comment]
> @jpuzz0 All lgtm, just have one request that's not related to this PR but I hope to see if it's possible to make changes here.
> 
> In #3140, I changed the icon for the artifact nodes based on the metrics type. However, looks like I only changed the icon when it's not hovered. If the node is hovered, the icon will be incorrect.
> 
> e.g. In the following 2 screenshot, the icon should be both monitoring icon, however, the second one is a list icon Screenshot 2024-10-21 at 5 09 01 PM Screenshot 2024-10-21 at 5 09 20 PM
> 
> The reason is I only updated https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx#L89, but didn't update https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx#L132 and https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx#L155 to use the `isMetricsArtifactType` function, which causes the inconsistency.
> 
> Could you update that in this PR because it's also about the icon/status? Thanks!

@DaoDaoNoCode I've updated this.

**Review by DaoDaoNoCode — APPROVED** [review]
Thanks, LGTM!
/lgtm

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm

**Pull request merged**
