### PR TITLE
v2.26.2-odh-release

### PR DESCRIPTION
**Pull request by mturley**
[18b67eb](https://github.com/opendatahub-io/odh-dashboard/pull/3241/commits/18b67eb97e3d62bf5117a7c486395d31d81aa8ae) includes changes from the [release instructions](https://spaces.redhat.com/pages/viewpage.action?spaceKey=RHODS&title=Dashboard+ODH+Release).

Also includes [84628b2](https://github.com/opendatahub-io/odh-dashboard/pull/3241/commits/84628b28ea751dc64377b303150b6edcc2d15123) which was merged to main after this release branch was created but we want to include.

### CODE REVIEW

**Comment by mturley** [comment]
/unhold
Just needed to make sure the digest was updated properly.

**Review by andrewballantyne — APPROVED** [review]

**Pull request merged**
