### PR TITLE
add data-testid to connection form fields

### PR DESCRIPTION
**Pull request by christianvogt**
## Description

Adds `field <env var>` `data-testid` to field control elements.
Replaces generated field IDs with `field-<env var>` values to ensure predicable IDs can be used with bitwarden.
Add `data-testid` to sections.

image

## How Has This Been Tested?

Web inspector

## Test Impact

Updated unit tests.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by christianvogt** [comment]
The original change had a test failure because of a test selector matching too many elements.
Made a small change to qualify the test id with `field` and also removed the test id from the label. This change aligns better with the original test ids in the data connections feature.

**Comment by christianvogt** [comment]
@emilys314 there was a conflict with test ids and one of the cypress tests so I made a new change to use a static test id for the control element which can be chained from the parent selector. Also noticed that one element did not pass through the test id.

**Comment by emilys314** [comment]
yeah that makes sense. 

I don't know if this version would fix Fede's and Jorge's original issue of the input fields themselves not having a unique identifier in the dom though. I don't know if bitwarden is able to do chaining.

Also the original data connections had the `data-testid` on the input themselves and not on the parent form group, is there any reason we have them there instead? (I suppose you can narrow down different elements for more complicated fields)

Screenshot From 2024-11-20 11-02-10

**Comment by emilys314** [comment]
/lgtm 

image

**Comment by jgarciao** [comment]
I've tested today's odh-nightly and now I'm able again to create bitwarden custom fields to populate the values. Thanks a lot, this will save us plenty of time!

**Pull request merged**
