### PR TITLE
Fix authorization header casing in storageUtils

### PR DESCRIPTION
**Pull request by Gkrumbach07**
closes: https://issues.redhat.com/browse/RHOAIENG-8473

## Description

changes header key to capital A

## How Has This Been Tested?

get image and test on cluster

## Test Impact

n/a backend

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]
/hold

Test on a cluster before merging. But lgtm.

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
For posterity -- this didn't work when we tested it on cluster. I asked Gage to change up the way we are calling for resources and use the `passThroughResource` utility instead of the K8s library. It is possible the K8s lib is overriding the Auth token no matter what.

**Review by andrewballantyne — APPROVED** [review]
Bingo, on cluster success!

**Comment by Gkrumbach07** [comment]
/unhold

tested on cluster

**Pull request merged**
