### PR TITLE
move and rename test files to align with their target file

### PR DESCRIPTION
**Pull request by christianvogt**
## Description

Test files should be located in a `__test__` directly co-located with the file being tested.

eg:
```
/src/pages/foo/bar.ts
/src/pages/foo/__tests__/bar.spec.ts
```

Some files did not follow this pattern and therefore this issue simply moves those tests to the correct location.

## How Has This Been Tested?

Run unit test automation.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
@christianvogt  The test file frontend/src/pages/modelServing/__tests__/modelPod.spec.ts needs to be inside frontend/src/pages/modelServing/screens/global/__tests__  and should be renamed

**Comment by christianvogt** [comment]
@pnaik1 I renamed and moved `modelPod.spec.ts`. I also ended up moving some additional tests into their appropriate spec files.

**Comment by ppadti** [comment]
@christianvogt  `frontend/src/api/__tests__/inferenceServices.spec.ts` and `frontend/src/api/__tests__/servingRuntimes.spec.ts ` these test files are not located inside api/k8s

**Comment by christianvogt** [comment]
@ppadti - @pnaik1 mentioned that she had those file move changes in https://github.com/opendatahub-io/odh-dashboard/pull/2408 and so I decided to not do another update here.

**Pull request merged**
