### PR TITLE
Support Caikit Serving Runtime with REST

### LINKED ISSUE #2058: [Story]: Support rest calls in caikit
### Goal

Support rest calls in caikit OOTB Custom Serving Runtime

### Dependency issue

No dependencies

### Itemized goals

Right now, the current OOTB Caikit Serving Runtime will only create a grpc route by default.

We need to update the image of caikit to one that only support REST.

### Aspects continued elsewhere

_No response_

### Mocks

No mocks

### PR DESCRIPTION
**Pull request by lucferbux**
Closes #2058 

## Description

Support Caikit with REST

## How Has This Been Tested?

1. Deploy this template
2. Deploy a new kserve model (I used `demo-models/flan-t5-small-caikit/flan-t5-small-caikit` in rhods-public)
3. Do an inference:

```bash
> export KSVC_HOSTNAME=$(oc get ksvc <inference-name>-predictor -n <namespace> -o jsonpath='{.status.url}' | cut -d'/' -f3) 
> curl -kL -H 'Content-Type: application/json' -d '{"model_id": "flan-t5-small-caikit", "inputs": "At what temperature does Nitrogen boil?"}' https://${KSVC_HOSTNAME}/api/v1/task/text-generation
```

## Test Impact

No automated testing

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by lucferbux** [comment]
@Xaenalt this is the preliminary work for the issue, once we have the final image we ca review and merge this!

**Comment by lucferbux** [comment]
Maybe we'll need a follow up, but merging with the current images

**Review by DaoDaoNoCode — APPROVED** [review]
/lgtm

**Pull request merged**
