### PR TITLE
Add duplicate option for non-OOTB custom serving runtimes

### LINKED ISSUE #1499: [FeatureRequest] Add option to duplicate a Custom Serving Runtime different from OOTB
As of now users can only duplicated Out-of-the-box serving runtime to create their own custom runtimes. However I think it could be useful to let users duplicating other Custom Serving Runtimes too.

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1499 

## Description

Simply add a dropdown option.

Now for OOTB custom serving runtimes:
Screenshot 2023-09-18 at 3 24 54 PM

For non-OOTB custom serving runtimes:
Screenshot 2023-09-18 at 3 25 33 PM

## How Has This Been Tested?

1. Import a new custom serving runtime or duplicate an OOTB serving runtime, to make a non-OOTB serving runtime
2. Check the dropdown menu of the new custom serving runtime
3. You should be able to duplicate the non-OOTB serving runtime now

## Test Impact

N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@vconzola Could you check the visual changes?

**Comment by vconzola** [comment]
@DaoDaoNoCode Can you take a screenshot of the Duplicate modal? I want to see what you're using for the modal heading and the runtime name. @katie is looking into inconsistencies in the current UI in simalr modals and we might as well do it right the first time in this one.

**Comment by DaoDaoNoCode** [comment]
@vconzola It's not going to a modal, it will go to a new page with the preset YAML code.

Screenshot 2023-09-18 at 3 53 16 PM

**Comment by lucferbux** [comment]
btw @vconzola we have https://github.com/opendatahub-io/odh-dashboard/issues/1727 to fix the inconsistency of "Add" instead "Duplicate" I'm gonna take that to see if we can fix it asap

**Comment by lucferbux** [comment]
/lgtm

Not approving until UX gives the lgtm too, I've added another comment to track the inconsistency we have right now for the "Duplicate" page.

**Comment by vconzola** [comment]
The dropdown change lgtm.

**Review by manaswinidas — APPROVED** [review]
/lgtm

Tested. Works fine.

**Pull request merged**
