### PR TITLE
Add useUser hook to EnsureCompatiblePipelineServer component

### PR DESCRIPTION
**Pull request by Gkrumbach07**
closes: https://issues.redhat.com/browse/RHOAIENG-5334

## Description

adjusts text dependent on admin or not
Screenshot 2024-04-11 at 2 14 54 PM
Screenshot 2024-04-11 at 3 42 05 PM

## How Has This Been Tested?

- log in as admin
- go to project with a v1 pipeline server -> see error message with delete button
- log in as regular user 
- go to project with a v1 pipeline server -> see error message without delete button

## Test Impact

none

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).
@kywalker-rh 
After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by kywalker-rh** [comment]
@Gkrumbach07 Only thing I see is the link in the Admin flow text should be on the next line. Otherwise this looks good to me.

**Comment by yannnz** [comment]
Content needs update. Please refer the mock: https://www.figma.com/proto/tMBCWHdmsk5qx79shNbGME/Invalid-Argo-Detection?type=design&node-id=76-1007&t=Zo9TOAtKc0GZZVDo-1&scaling=scale-down-width&page-id=0%3A1&mode=design

**Comment by jgarciao** [comment]
Will the notice be shown in all these pages? 
- Data Science Projects > Overview
- Data Science Projects > Pipelines
- Data Science Pipelines  > Pipelines
- Data Science Pipelines  > Runs

**Comment by kywalker-rh** [comment]
lgtm Approved from UX

**Review by lucferbux — APPROVED** [review]
/lgtm

**Pull request merged**
