### PR TITLE
feat(15588): mr style updates

### PR DESCRIPTION
**Pull request by gitdallas**
closes: https://issues.redhat.com/browse/RHOAIENG-15588

## Description
mr style updates

## How Has This Been Tested?

- the edit icon should be at the start of button for editableTextDescriptionListGroup (which is used in MR details and MR version details). this component is not used anywhere else.
image
image

- register new version on the model versions list page should be primary:
image

- actions button should be secondary on the model detail and versions list page:
image

- version detail page should have a separate button with primary styling for deploy (removed from actions menu), and the actions button should be secondary styling
image
image

## Test Impact
none - styling changes

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change. @yih-wang 

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by mturley** [comment]
@yih-wang looking at this actions dropdown, now that the deploy action is removed from it it only has one action. should we maybe just change it so there is a secondary "Archive model version" button instead of the actions dropdown? I suppose that will take up more space.

**Comment by mturley** [comment]
@gitdallas I don't see this change mentioned on the issue: register new version on the model versions list page should be primary
image
@yih-wang can I confirm that we want this?

**Comment by yih-wang** [comment]
@mturley sorry I didn't write down all the details in the Jira description... But yes, the `register new version` button should change to primary while the `Actions` dropdown downgrades to a second style.

**Comment by yih-wang** [comment]
LGTM, thanks @gitdallas !

**Comment by mturley** [comment]
Ah thanks! I missed that. LGTM!

**Pull request merged**
