### PR TITLE
Update empty pipeline server page button variant

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
JIRA: https://issues.redhat.com/browse/RHOAIENG-9209

## Description

Updated the configure server button variant on pipelines page to make it primary.

Screenshot 2024-10-04 at 11 43 28 AM

## How Has This Been Tested?

Go to the project that doesn't have a pipeline server configured, make sure the configure server button is the primary style on both the projects page and the pipelines global page.

## Test Impact

N/A, minor UX update.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
We do have a `Configure pipeline server` button in the overview page, Are we not supposed to change that as well?

Screenshot 2024-10-07 at 5 09 15 PM

**Comment by DaoDaoNoCode** [comment]
@pnaik1 I don't think so, that's in a card and we should align the button style with other cards, and keep it as a link variant.

Screenshot 2024-10-09 at 9 43 26 AM

**Review by dpanshug — APPROVED** [review]
/lgtm 

the buttons are updated on project pipeline and global pipeline page.
Screenshot 2024-10-09 at 8 18 31 PM

**Comment by Gkrumbach07** [comment]
i agree i think the card needs to stay as link due to the other cards having their action buttons be link too. The jira was concerned with our full pages not using the primary variant

so this lgtm

/approve

**Comment by yannnz** [comment]
Sorry there is a vpn isuse in Beijing office, those comments didn't show up to me. I think this looks good to me.

**Pull request merged**
