### PR TITLE
support better handling of name and description in import pipeline modal

### PR DESCRIPTION
**Pull request by pnaik1**
https://issues.redhat.com/browse/RHOAIENG-14617

## Description
The name and description for the `import pipeline/ pipeline version modal` now has a max limit of 255
the submit button is disbaled if the name is duplicated

Screenshot 2024-11-22 at 1 07 58 PM

Screenshot 2024-11-22 at 1 08 21 PM

## How Has This Been Tested?

1. Create a pipeline using `import pipeline modal` with name larger character set
2. Verify for the helperText 
3. Verify that the name gets trim after 255 character is achieved
4. Verify that when duplicated name is typed the `submit button` is disabled with error helperText

## Test Impact
N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
cc @yannnz , Can you have a look at the screenshot? 

- added a helperText below the `Pipeline name` and `Pipeline description` 

- I have disabled the `submit button` and indicated an error when pipeline already exists

**Comment by yannnz** [comment]
Based on the new UI guideline Anges is working on, it looks like the error message is right below the field. The   
Screenshot 2024-11-22 at 21 44 32

[UI guideline](https://docs.google.com/document/d/1qEKzhWEDKQEPce3Zm_4ET6ci7Kkc55vegOZ0a5ORHBU/edit?usp=sharing)

I need to double check with her in slack if this is finalized. I cannot find her Github account.

**Review by Gkrumbach07 — COMMENTED** [review]
code and functionality looks good. lets just update the base component to match new UX guidelines

**Comment by nding-anges** [comment]
Hi @yannnz, thank you for pointing that out. I have a question: should the name field include helper text to inform users that the name cannot be duplicated?  If yes, for showing multiple helper text under a field, there is [a design pattern](https://docs.google.com/document/d/1qEKzhWEDKQEPce3Zm_4ET6ci7Kkc55vegOZ0a5ORHBU/edit?tab=t.0#bookmark=id.fmjq5kx0gohq) that outlines how to display multiple helper texts underneath the field, as well as how to indicate an error status for each helper text.d as well as how to show an error status for each of helper text. 
截屏2024-11-25 15 49 09

**Comment by simrandhaliw** [comment]
> @nding-anges I would say a system doesn't support duplicated name seems a common way in many websites. It is not that special that UI always needs to point it out. Unless we allow duplicated names in our system in other flows.

Agreed!

**Review by DaoDaoNoCode — APPROVED** [review]
The UX feedback is addressed.
/lgtm

**Pull request merged**
