### PR TITLE
make explore card clickable with PF work around

### PR DESCRIPTION
**Pull request by christianvogt**
Fixes https://issues.redhat.com/browse/RHOAIENG-3773

## Description

PF selectable cards has are not functional in website v122.
PF has introduced a fix and this change applies that fix while waiting to adopt the latest PF release.

_note commits need to be squashed_

## How Has This Been Tested?

Navigate to the explore page and click the Jupiter tile.

## Test Impact

Existing cypress tests were failing with chrome v122. This change should see that test pass.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by evwilkin** [comment]
@christianvogt FYI we've release patch `5.2.1` which should resolve this issue related to a recent Chromium update ([details here](https://github.com/orgs/patternfly/discussions/6381)).  

Apologies for any inconvenience, we're discussing next steps to avoid or proactively catch issues from new browser releases moving forward.

**Comment by christianvogt** [comment]
Thanks @evwilkin we will do a followup to update to latest PF and remove the workaround.

**Pull request merged**
