### PR TITLE
Workbench toggle changing state

### PR DESCRIPTION
**Pull request by pnaik1**
https://issues.redhat.com/browse/RHOAIENG-9988
https://issues.redhat.com/browse/RHOAIENG-6485

## Description
If a Workbench is stopped/started using toggle via the Workbench tab inside Data science Projects, the state is updated in the projects view. Likewise, if a workbench is stopped/started via the projects view toggle, it will be updated

## How Has This Been Tested?

1. Create a Data Science Project
2.  Create a new workbench
3.  Open your project in a new browser tab
4. Navigate to the Workbenches tab and verify your workbench is in 'Running' state.
5. In Projects browser tab, observe its in running state
6. Use both browsers to change the toggle states and observe correct behaviours

## Test Impact
N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by Gkrumbach07 — CHANGES_REQUESTED** [review]
This causes the page to poll unnecessarily now. The jira's solution is to use web sockets

**Comment by pnaik1** [comment]
@Gkrumbach07 I forgot to mention it here, but I had this conversation about using websocket  in the channel [thread](https://redhat-internal.slack.com/archives/C05SMJ09DD2/p1724932869246499).

**Comment by pnaik1** [comment]
@Gkrumbach07 
1. Thanks, I was unaware of this `useRefreshInterval` hook, I can replace this
2. `useRefreshNotebookUntilStartOrStop` polls until the notebook is stopped or running, since we are now polling irrespective of which state the notebook is, I think using `useRefreshNotebookUntilStartOrStop` will be a duplicacy, added more unnecessary polling

**Comment by pnaik1** [comment]
Updated the PR accordingly

**Comment by Gkrumbach07** [comment]
this looks good to me

/lgtm

**Review by jpuzz0 — APPROVED** [review]
Tested locally and works as described.

**Pull request merged**
