### PR TITLE
Fetch prometheus metrics from UWM

### PR DESCRIPTION
**Pull request by alexcreasy**
Closes: 
 * #1855
 * #1916
 * #1109
## Description

* Migrates prometheus metrics queries for explainability and performance to use UWM.
* Modifies model performance queries to use model mesh native prometheus function instead of `haproxy` (haproxy functions don't work with UWM.

Notes: 
* A dashboard build with these changes is available here: quay.io/acreasy/odh-dashboard:uwm

## How Has This Been Tested?

Requires a DS project with a model server installed, TrustyAI service installed and some models to test. You'll also need to fire some data at the model.

Note: this can't be tested locally in dev mode as the queries need to be made via RBAC, which isn't available via external routes, use the image listed above to test.

Run these tests as a cluster admin and also as a user with admin role on the ds project to verify.

For your given test model:
1. Open the model server metrics view, verify data is shown on the various charts.
2. Open the model metrics view, verify the Performance metrics work as expected - i.e. that the charts show plotted data and respond to the controls.
3.  Navigate to the bias tab and verify that data is plotted on the charts and the controls respond as expected.

## Test Impact

No tests at this time, I'll create an issue for testing this issue as a whole after.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [x] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by shalberd** [comment]
out of interest:
are you using port 9091 (all-or-nothing clusterrole) or port 9092 with url parameter "namespace" for Thanos?

https://cloud.redhat.com/blog/thanos-querier-versus-thanos-querier

**Comment by alexcreasy** [comment]
Hey @shalberd,

Excellent question, we'll be using the 9092 port with url param `namespace` - this seemed to make the most sense as the 9091 port requires users to have pretty high privileges to make the query - the kind your average data science user is unlikely to have!

**Comment by alexcreasy** [comment]
@shalberd So that's the issue I'm running face first into - haproxy metrics don't work with the updated implementation!!! Thanks for the info, I'm going to read through the thread you linked to and try to get an understanding of this!

CC: @VedantMahabaleshwarkar I don't know if you're still struggling with the haproxy queries - if so it's probably worth reading the thread Sven has linked above as it could well throw some light on the problem!

**Comment by alexcreasy** [comment]
The PR has been updated  to fetch metrics from UWM. Model performance metrics are now based on native modelmesh query functions rather than the previous `haproxy` which do not work via UWM.

**Comment by Gkrumbach07** [comment]
Bias data comes through fine with graphs showing data, however model metrics data is not showing up in the performance metrics tab

**Comment by shalberd** [comment]
> Model performance metrics are now based on native modelmesh query functions rather than the previous haproxy which do not work via UWM.

Very cool, that way, you save yourself the hassle of having to deal with openshift-ingress and getting that secret into the odh namespace. 

Being able to rely on UWM / Monitoring for User Defined Projects with ServiceMonitor or PodMonitor CRs in the namespaces is awesome. Thank you all so much, and thanks to people higher up at RedHat that finally gave the go-ahead on UWM.

**Comment by Gkrumbach07** [comment]
Did a re-review with new data and all graphs show with data flowing

/lgtm

**Comment by pnaik1** [comment]
/lgtm 
Working as expected

**Pull request merged**
