### PR TITLE
Fix odh release

### LINKED ISSUE #1123: [Bug]: Latest node 18 release is breaking the dashboard
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Based on the comments on https://github.com/opendatahub-io/odh-manifests/pull/770

We are experiencing some issues with the latest version of the dashboard

```bash
> ods-dashboard-backend@1.0.0 start
> NODE_ENV=production node ./dist/server.js --log=1 --registry=localhost:50051

npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /opt/app-root/src/.npm/_cacache/tmp/a99da38d
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000690000:0 "/opt/app-root/src/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /opt/app-root/src/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

We should revert to the latest image to avoid this issue until we find a proper solution

### Expected Behavior

Dashboard is deployed successfully.

### Steps To Reproduce

_No response_

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Fixes #1123 

## How Has This Been Tested?

1. Create a new build
2. Deploy it and check there is no error

## Request review criteria:

- [ ] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by lucferbux** [comment]
> @lucferbux this is mergable, no? We can't _really_ test this change until it gets to RHODS and part of that build process?

Yes, that's right, this can be merge, and @DaoDaoNoCode can use this for his development.

**Comment by lucferbux** [comment]
> @lucferbux this is mergable, no? We can't _really_ test this change until it gets to RHODS and part of that build process?

Yes, that's right, but this won't affect RHODS in any means, we use a different Dockerfile downstream so this is targeted only for Upstream release.

**Comment by andrewballantyne** [comment]
> > @lucferbux this is mergable, no? We can't _really_ test this change until it gets to RHODS and part of that build process?
> 
> Yes, that's right, but this won't affect RHODS in any means, we use a different Dockerfile downstream so this is targeted only for Upstream release.

Thanks for the clarification. Is there anyway for us to test this upstream? How do we know this is the desired change? Was the same change done downstream and it worked?

**Comment by lucferbux** [comment]
> > > @lucferbux this is mergable, no? We can't _really_ test this change until it gets to RHODS and part of that build process?
> > 
> > 
> > Yes, that's right, but this won't affect RHODS in any means, we use a different Dockerfile downstream so this is targeted only for Upstream release.
> 
> Thanks for the clarification. Is there anyway for us to test this upstream? How do we know this is the desired change? Was the same change done downstream and it worked?

This same change was done downstream, we are currently shipping with this image, I've tested a local image with this changes and it seems to be working in my dev environment and as per @LaVLaS commented in a private channel, testing http://quay.io/opendatahub/odh-dashboard:main-a317f55 with the release PR seems to work.

**Review by andrewballantyne — APPROVED** [review]

**Pull request merged**
