### PR TITLE
Revamp Model framework label text

### LINKED ISSUE #1458: [Bug]: OOTB model serving framework descriptions are not intuitive
### Feature description

When deploying a model within projects, the Ui has a field for 'Model framework'. The options in this field are not intuitive. The OOTB option names should be modified. 

Options are:

"openvino_ir - opset1" - not sure what this is, but not intuitive
"onnx - 1" - should probably be capitalized "ONNX", do we need the '-1'? 

### Anything else?

This UI is generated by these fields:

```yaml
supportedModelFormats:
  - autoSelect: true
    name: openvino_ir
    version: opset1
  - autoSelect: true
    name: onnx
    version: '1'
```

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Closes #1458 

## How Has This Been Tested?

1. Go to DS Project
2. Deploy a model server
3. Go to the `Deploy model` modal
4. Check that the Model framework label now is displayed as `Model framework (name - version)`

Screenshot 2023-07-10 at 13 37 35

## Test Impact

Added extra steps in integration of Create model

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] The commits have meaningful messages (squashes happen on merge by the bot).
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [X] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by lucferbux** [comment]
@vconzola I'm only changing the field label as you suggested, we've discussed this internally but let me know if it's ok!

**Comment by lucferbux** [comment]
Ok, based on internal conversations, this PR should be ready to go!

**Comment by andrewballantyne** [comment]
/lgtm

Screenshot looks great.

**Pull request merged**
