### PR TITLE
Adapt model deployment modals to the latest design

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
JIRA: [RHOAIENG-10134](https://issues.redhat.com/browse/RHOAIENG-10134)

## Description

Change the layout and some texting based on the mockup here https://www.figma.com/design/oWUToVG5TikXyDGFHNIK87/Model-Serving-post-Summit-2024?node-id=2115-20976&t=A5cSaE6FTIX2bRjx-0

1. Make the project name bold in the alert if there is an error with the project when deploying the model version
Screenshot 2024-08-19 at 12 57 39 PM

2. Multi-model platform
Screenshot 2024-08-19 at 12 58 43 PM

3. Single-model platform
Screenshot 2024-08-19 at 12 59 09 PM
Screenshot 2024-08-19 at 12 59 22 PM

## How Has This Been Tested?

1. Check the deployment modal for both multi-model platform projects and single-model-platform projects
2. Make sure the layout is aligned with the mockup and the function is working as expected

## Test Impact

N/A, UX updates, I only updated the cypress test a little bit due to the text and layout changes

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@vconzola Could you check the screenshots above to see if it meets your expectations?

**Comment by vconzola** [comment]
@DaoDaoNoCode  I think these look OK. One minor thing - for multi-server, the field label should be "Model server", not "Model servers". Thanks.

**Comment by mturley** [comment]
@vconzola I'll deploy an image of this on a cluster for you to play with and DM you the details on Slack.

**Comment by jpuzz0** [comment]
Looks like in the mockup, the field widths take up 3/4 of the width of the modal. Was that not an intended change for this design update?

**Comment by DaoDaoNoCode** [comment]
> Looks like in the mockup, at most the field widths take up 3/4 of the width of the modal. Was that not an intended change for this design update?
This is a good question for @vconzola, I can change it to take 3/4 of the width of the modal if you want. But it's a good thing to discuss with the team first if we want to make this change because all the other modals use the full width and I believe we want to keep consistency across the whole product.

**Comment by vconzola** [comment]
@jpuzz0 @DaoDaoNoCode The field widths should be consistent with other modals. The 3/4 thing was just me not being careful in the mockups. Sorry for the confusion.

**Comment by mturley** [comment]
This LGTM aside from the test failure @DaoDaoNoCode

**Comment by DaoDaoNoCode** [comment]
@mturley This is due to the flaky test and that will be fixed in another ticket. I am re-running the test in this PR to make sure it passes all the tests.

**Review by mturley — APPROVED** [review]
LGTM, tested locally

**Pull request merged**
