### PR TITLE
Fix the replica count for kserve

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Closes https://issues.redhat.com/browse/RHOAIENG-164

## How Has This Been Tested?

1. Create a new Project
2. Select to deploy a kserve model (single model)
3. Change the replica count
4. Deploy the model
5. Now go to the openshift console, to the acutal deployment
6. Check that the number of replicas match the ones selected

Screenshot 2024-01-09 at 23 57 36

## Test Impact

Added unit testing for the assenble function

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by lucferbux** [comment]
@dpanshug @mturley Can you guys review this please?

**Comment by mturley** [comment]
@lucferbux the code LGTM, but I'm having an issue testing it locally.

* Testing on the real cluster-hosted UI (kserve-pm), I can reproduce the bug (the deployment gets created with 1 pod instead of 2 when I specify 2 replicas).
* Testing on both the main branch and the PR with my local UI pointed at the same cluster (kserve-pm), the deployment never gets created regardless of how many replicas I specify.

**Comment by lucferbux** [comment]
> @lucferbux the code LGTM, but I'm having an issue testing it locally.
> 
> * Testing on the real cluster-hosted UI (kserve-pm), I can reproduce the bug (the deployment gets created with 1 pod instead of 2 when I specify 2 replicas).
> * Testing on both the main branch and the PR branch with my local UI pointed at the same cluster (kserve-pm), the deployment never gets created regardless of how many replicas I specify.

@mturley I've just tested it and it should be working, test it with low replicas to be able to deploy it.

Screenshot 2024-01-17 at 18 37 02

**Review by mturley — APPROVED** [review]
LGTM aside from merge conflicts

**Pull request merged**
