### PR TITLE
create error boundaries for app and content

### PR DESCRIPTION
**Pull request by christianvogt**
Closes: #1554

## Description

Whenever an uncaught exception occurs in the UI, an error page will display the error details instead of simply rendering a blank page.

The error boundary is installed at two different locations:
- top level
image

- main content
image

## How Has This Been Tested?

Added a storybook story for rendering the ErrorBoundary.

Created a component which throws an exception:
```
const Throw = () => {
  throw new SyntaxError('This is only a test.');
};
```

Render this component in various parts of the app; both inside the main content area and outside (eg navigation).
```
<Throw />
```

## Test Impact

Impacts, in a positive way, uncaught exceptions thrown by the application to display errors instead of blank page.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

cc @kaedward @kywalker-rh

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@kywalker-rh @kaedward This is our "better than whitescreening" solution. Let us know if you prefer a different design. Take a look at the issue to see examples in OpenShift Console & HAC doing something similar.

**Comment by kaedward** [comment]
@andrewballantyne Definitely better than a blank screen! The only note I have is about the title: "Oh no! Something went wrong." 
I'd suggest something a little more descriptive, if possible... or just removing the "oh no!" :-) 
How about "Something went wrong." or "An error occurred." ?

**Comment by christianvogt** [comment]
I've updated the message to `An error occurred.`

**Review by lucferbux — APPROVED** [review]
/lgtm

Wow this is a really nice to have improvement 👍

**Pull request merged**
