### PR TITLE
Fix inconsistency in authentication

### PR DESCRIPTION
**Pull request by lucferbux**
Closes https://issues.redhat.com/browse/RHOAIENG-382

## Description

Fix inconsistency in authentication working for model serving.

Screenshot 2024-05-23 at 02 38 16

## How Has This Been Tested?

1. Deploy a model through KServe
2. Select external route
3. Text should match "Token authentication"

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by lucferbux** [comment]
[TBD] I'll add the testing later this week, still waiting on https://issues.redhat.com/browse/RHOAIENG-5222 to check the full implementation detals

cc @VedantMahabaleshwarkar

**Comment by lucferbux** [comment]
@kaedward @vconzola can you guys take a look at this?

**Comment by vconzola** [comment]
@lucferbux I'm not sure what we're supposed to be looking at. The change was just to replace "authorization" with "authentication" throughout, correct? It looks like your PR does that. Is there anything else we need to review? cc: @kaedward

**Comment by lucferbux** [comment]
> @lucferbux I'm not sure what we're supposed to be looking at. The change was just to replace "authorization" with "authentication" throughout, correct? It looks like your PR does that. Is there anything else we need to review? cc: @kaedward

Oh yes, that was it, just to confirm those were the changes

**Review by gitdallas — APPROVED** [review]

**Pull request merged**
