### PR TITLE
Update error message when importing custom notebook image

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
JIRA: https://issues.redhat.com/browse/RHOAIENG-389

## Description

Simply update the error message returned by the backend.

Before:

Screenshot 2024-09-25 at 11 49 16 AM

After:

Screenshot 2024-09-25 at 11 52 31 AM

## How Has This Been Tested?

1. Import a custom notebook image
2. Import another custom notebook image with the same name
3. Check the error message

## Test Impact

N/A, backend change.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
Verified locally, works well

Screenshot 2024-09-26 at 1 09 10 PM

This might not be related to this issue, but can we have a helperText below the `Name` field informing the user its `resource name` because the name displayed in the error text and the name typed doesn't match, might be misleading

**Comment by DaoDaoNoCode** [comment]
@Gkrumbach07 Maybe we should leverage the name description field created by Andrew in another PR into this? What do you think?

**Comment by Gkrumbach07** [comment]
@DaoDaoNoCode Yeah that would be good. Can you create a jira to track down this

**Comment by DaoDaoNoCode** [comment]
I created a JIRA ticket for the name and description field. This PR should be ready to be reviewed.

**Pull request merged**
