### PR TITLE
Add data-ids where possible

### PR DESCRIPTION
**Pull request by maroroman**
Adds data-ids to buttons checkboxes and radio buttons

## Description
Data-ids are added for:

- User Management:
  - Save changes
- Cluster Settings:
  - PVC Size input
  - Restore Default
  - Culling Unlimited radio
  - Culling Limited radio
  - Hour/Minute Inputs
  - Toleration Checkbox
  - Data gathering checkbox 
  - Save Changes
- BYON:
  - Import image
  - Repository input
  - Name input
  - Description Input
  - Software/Package Tabs
  - Add Software/Package (Outer/Inner)
  - Import
  - Cancel 
  - Same for update image modal
  - Edit 
  - Delete 
- Spawner
  - Spawner Tab 
  -  Images - Radio buttons
  -  Sizes dropdown (Skipped)
  - GPU dropdown (Skipped)
  - Env var Dropdown (Skipped)
  - Envvar var input
  - Envar value input
  - Secret checkbox
  - Start
  - Cancel
- Status
  - Return
  - Stop
- Administration
  - Admin tab  
  - Start server
  - Stop all servers
  - Stop server
- Learning center 

## How Has This Been Tested?
1. Deploy the ODH Dashboard
2. Verify presence of data-id in mentioned elements

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by dlabaj** [comment]
@andrewballantyne Thoughts on using OUIA instead of data ids.  Kafka went with data ids originally then had to switch OUIA.

**Comment by andrewballantyne** [comment]
I'm indifferent @dlabaj 

I totally forgot about this PR, sorry @maroroman -- OUIA or data-id are fine with me -- we just have to convey this to QE. I imagine their automation can use either, but I don't know what they are doing right now.

**Comment by DaoDaoNoCode** [comment]
Yeah, I think it is based on the tag that QE relied on for testing. If they want to move to OUIA id in the future we can convert them then by simply using one button replace.

**Comment by dlabaj** [comment]
okay if this is what they use.

**Review by dlabaj — APPROVED** [review]
/lgtm

**Pull request merged**
