### PR TITLE
Duplication of volumes of a Workbench

### PR DESCRIPTION
**Pull request by dpanshug**
[RHOAIENG-14654](https://issues.redhat.com/browse/RHOAIENG-14654)

## Description
Added a condition to remove the volume mount if it already exists with a different mount path, and replace it with the source path when adding a PVC from the spawner page.

## How Has This Been Tested?
Follow the steps mentioned in JIRA.

## Test Impact
N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
The commit here is what caused the issue. you just need to revert parts of it
https://github.com/opendatahub-io/odh-dashboard/pull/3231/files#diff-dedc11348a77f96be1b5c9866b27a5d61a20010f6a98eea6dca816d59d9acba8L24-R23

here is the diff of what im talking about

```diff
diff --git a/frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx b/frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
index a4b847d9f..013cdcc9e 100644
--- a/frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
+++ b/frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
@@ -38,7 +38,11 @@ import ContainerSizeSelector from './deploymentSize/ContainerSizeSelector';
 import StorageField from './storage/StorageField';
 import EnvironmentVariables from './environmentVariables/EnvironmentVariables';
 import { useStorageDataObject } from './storage/utils';
-import { getCompatibleAcceleratorIdentifiers, useMergeDefaultPVCName } from './spawnerUtils';
+import {
+  getCompatibleAcceleratorIdentifiers,
+  getRootVolumeName,
+  useMergeDefaultPVCName,
+} from './spawnerUtils';
 import { useNotebookEnvVariables } from './environmentVariables/useNotebookEnvVariables';
 import DataConnectionField from './dataConnection/DataConnectionField';
 import { useNotebookDataConnection } from './dataConnection/useNotebookDataConnection';
@@ -237,7 +241,11 @@ const SpawnerPage: React.FC<SpawnerPageProps> = ({ existingNotebook }) => {
                 isInline
                 title="Cluster storage will mount to /"
               />
-              <StorageField storageData={storageData} setStorageData={setStorageData} />
+              <StorageField
+                storageData={storageData}
+                setStorageData={setStorageData}
+                editStorage={getRootVolumeName(existingNotebook)}
+              />
             </FormSection>
             {isConnectionTypesEnabled ? (
               <ConnectionsFormSection
diff --git a/frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx b/frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
index 16235a569..123afa02d 100644
--- a/frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
+++ b/frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
@@ -4,13 +4,14 @@ import { ExistingStorageObject } from '~/pages/projects/types';
 import { ProjectDetailsContext } from '~/pages/projects/ProjectDetailsContext';
 import { getDisplayNameFromK8sResource } from '~/concepts/k8s/utils';
 import TypeaheadSelect from '~/components/TypeaheadSelect';
-import useProjectPvcs from '~/pages/projects/screens/detail/storage/useProjectPvcs';
+import useAvailablePvcs from './useAvailablePvcs';
 
 type AddExistingStorageFieldProps = {
   data: ExistingStorageObject;
   setData: (data: ExistingStorageObject) => void;
   selectDirection?: 'up' | 'down';
   menuAppendTo?: HTMLElement;
+  editStorage: string;
 };
 
 const AddExistingStorageField: React.FC<AddExistingStorageFieldProps> = ({
@@ -18,9 +19,17 @@ const AddExistingStorageField: React.FC<AddExistingStorageFieldProps> = ({
   setData,
   selectDirection,
   menuAppendTo,
+  editStorage,
 }) => {
-  const { currentProject } = React.useContext(ProjectDetailsContext);
-  const [storages, loaded, loadError] = useProjectPvcs(currentProject.metadata.name);
+  const {
+    currentProject,
+    notebooks: { data: allNotebooks },
+  } = React.useContext(ProjectDetailsContext);
+  const [storages, loaded, loadError] = useAvailablePvcs(
+    currentProject.metadata.name,
+    allNotebooks,
+    editStorage,
+  );
 
   const selectDescription = (size: string, description?: string) => (
     <div>
diff --git a/frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx b/frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
index 0e2ac7515..73f0dfc19 100644
--- a/frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
+++ b/frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
@@ -8,9 +8,10 @@ import AddExistingStorageField from './AddExistingStorageField';
 type StorageFieldType = {
   storageData: StorageData;
   setStorageData: UpdateObjectAtPropAndValue<StorageData>;
+  editStorage: string;
 };
 
-const StorageField: React.FC<StorageFieldType> = ({ storageData, setStorageData }) => {
+const StorageField: React.FC<StorageFieldType> = ({ storageData, setStorageData, editStorage }) => {
   const { storageType, creating, existing } = storageData;
 
   return (
@@ -54,6 +55,7 @@ const StorageField: React.FC<StorageFieldType> = ({ storageData, setStorageData
                   setData={(data) => setStorageData('existing', data)}
                   selectDirection="up"
                   menuAppendTo={getDashboardMainContainer()}
+                  editStorage={editStorage}
                 />
               )
             }

```

**Comment by dpanshug** [comment]
@Gkrumbach07 thanks, i thought we need to support changing root cluster storage.

**Comment by Gkrumbach07** [comment]
@dpanshug This will likely need to change with Jeffs PR so we should also hold this until then and revaluate if the issue is still there

/hold

**Comment by Gkrumbach07** [comment]
@dpanshug is this still valid

**Comment by dpanshug** [comment]
@Gkrumbach07 after validating the main branch, the bug does not exists anymore. Hence closing this PR.

**Pull request closed without merging**
