### PR TITLE
Fix for when topology has visual runAfters in use

### PR DESCRIPTION
**Pull request by andrewballantyne**
Closes: #1233

## Description

Uses the `runAfter` state if any of the nodes have it -- to prevent mixing and matching and potentially causing duplicate lines.

From:
image

To:
image

## How Has This Been Tested?

Using a Pipeline that has runAfter usage to view the Pipeline. Let me know if you need to see my example, it's taken from another source and I'm not sure how public that is.

## Test Impact

None -- no tests.

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by lucferbux** [comment]
@andrewballantyne I've tried to set up a pipeline like this to test it, and I couldn't manage it, I've reviewed the code but didn't fully test the functionality, can you share me an example on how to deploy this kind of pipelines?

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm

got it working in the UI and it works as expected

**Comment by Gkrumbach07** [comment]
This is a smallish feature/bug fix with 2 LGTM tags. 

/approve

**Comment by lucferbux** [comment]
[Updated] I've managed to test it, works fine. cc @andrewballantyne 

Screenshot 2023-05-18 at 15 50 59

**Pull request merged**
