### PR TITLE
feat(dw): top consumption charts

### PR DESCRIPTION
**Pull request by gitdallas**
Closes: https://issues.redhat.com/browse/RHOAIENG-2845

## Description
implement top consuming distributed workload charts

left some utility type stuff in the consuming chart component, this and the inner pf chart will be moved out once we get this and other chart stuff in and are able to combine/refactor a bit.

No workloads:
image
No workloads consuming resources (similar message for if all or some have failed, but using <!> icon and noting that some or all have failed):
image
image
image
With data
image
With narrow screen:
image

## How Has This Been Tested?
Ran through with various data and lack of data

## Test Impact
tests for the empty state of this session are in place, not sure if we are testing charts

## Request review criteria:
empty state works (no workloads, no workloads with usage), if workloads with usage exist, two donut charts should show the details of that usage.

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
"Memory by cores"? Shouldn't that be MiB or GiB or something?

The tooltip on the chart doesn't have a unit
image

**Comment by gitdallas** [comment]
@andrewballantyne - fixed, made a typo when i refactored earlier

**Review by andrewballantyne — APPROVED** [review]
We will need tests and separation of utilities from component files. But that's minor among just getting the features set.

**Comment by andrewballantyne** [comment]
@gitdallas you have lint errors, please cleanup those.

**Comment by andrewballantyne** [comment]
/override ci/prow/images ci/prow/odh-dashboard-pr-image-mirror

**Pull request merged**
