### PR TITLE
Add deployment to global view and fix status

### LINKED ISSUE #1956: [Story]: Adapt Global Deploy Model Modal
### Goal

Adapt the Deploy Model Modal in the global view to either display the fields for kserve or modelmesh

### Dependency issue

* https://github.com/opendatahub-io/odh-dashboard/issues/1948

### Itemized goals

* Make sure we are filtering the projects that don't have the `modelmesh-enabled: ...` label
* Adapt the modal to show the project selection first
* Add the logic to either display kserve modal or modelmesh modal depending on the project selection
* Add the logic to deploy the correct `InferenceService` and `ServiceRuntime`

### Aspects continued elsewhere

_No response_

### Mocks

* https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/MmnvOYz
* https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/5nWmEg8

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Closes #1956 

### No projects
1. Delete all projects
2. Go to model serving global
3. Check that the **No data science projects** view is rendered
Screenshot 2023-11-10 at 17 12 26

### Wrong project
1. Go to model serving global
2. Add to the URL `modelServing/<path-to-wrong-object>`
3. Check that the **Project not found** image is rendered
Screenshot 2023-11-10 at 17 19 47

### No models deploy in a new project
1. Go to model serving global
2. Select a newly create project **with no serving platform selected**
3. Check that you get the "no deployed model" view

Screenshot 2023-11-10 at 17 23 14

### Deploy a model in modelmesh
1. Create a new project and select modelmesh as the serving platform
2. Go to model serving global
3. Click `Deploy model`
4. Check that the modelmesh modal is shown

Screenshot 2023-11-10 at 17 11 09

### Deploy a model in kserve
1. Create a new project and select kserve as the serving platform
2. Go to model serving global
3. Click `Deploy model`
4. Check that the modelmesh modal is shown

Screenshot 2023-11-10 at 17 10 44

### List all resources
1. Go to model serving global
2. Check that you render all the resources

Screenshot 2023-11-10 at 17 10 15

### Filter by project
1. Go to model serving global
2. Filter by project
3. Check that only the right resources are rendered in the table

Screenshot 2023-11-10 at 17 10 23

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [X] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by lucferbux** [comment]
@vconzola can you take a look at this please?

**Review by DaoDaoNoCode — APPROVED** [review]
/lgtm
Peer coding with @lucferbux and running everything.

**Comment by vconzola** [comment]
@lucferbux A few comments...

1. For the "No models deploy in a new project" scenario, is this behavior consistent with the way pipelines handles the same scenario? It should be.
2. I think we need an additional empty state for the case where there the user has selected a serving platform for a project but hasn't deployed any models yet. We should show an empty state within the table with a deploy action button. (This might be handled automatically for our tables already?)

**Pull request merged**
