### PR TITLE
[WIP] Add endpoint for moving volumes

### PR DESCRIPTION
**Pull request by maroroman**
Resolves: #603 

## Description
This PR adds a utility function adn an endpoint which allows the dashboard to move PVCs.

Note:
If the PVC has a consumer, even if the dashboard sends a delete command, it will be stuck terminating due to being protected by a finalizer. These have to be deleted manually by patching out the finalizer.
The PV is mostly untouched, but it probably should be documented somewhere that this is a somewhat dangerous operation and data should be backed up just in case.

## How Has This Been Tested?
1. Create a target namespace
2. Send a PATCH request to the `/api/volumes` endpoint with the following body: `{"name": <copied PVC name>, "tgtNamespace": <target Namespace>, "srcNamespace": <source Namespace>}` (srcNamespace is optional, if left out, dashboard namespace is used)
3. The request should return the newly created PVC which is a copy of the previous one, but in the target namespace.
4. Verify that the PVC and PV are correctly bound.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by andrewballantyne** [comment]
/hold

This is a dangerous flow if we mess it up. We need to test this a lot.

**Comment by maroroman** [comment]
> /hold
> 
> This is a dangerous flow if we mess it up. We need to test this a lot.

Ok definitely will test it with some rigor, any specific cases that you want me to check @andrewballantyne ?

**Comment by andrewballantyne** [comment]
No this should not be able to be done by a non-admin. Let's keep this limited as much as possible.

Glad you were able to test it more and find gaps, this was my concern. We should come up with a plan and talk it through with Landon and Chris to make sure we are all on the same page.

**Comment by cfchase** [comment]
> No this should not be able to be done by a non-admin. Let's keep this limited as much as possible.
> 
> Glad you were able to test it more and find gaps, this was my concern. We should come up with a plan and talk it through with Landon and Chris to make sure we are all on the same page.

I assume this will be used in the future migration out of the notebooks namespace but is not called from any front end code yet.  I'm not sure this would even need a it's own route if that's the case.  I would disable the route or comment it out for now until you use it as part of that flow.  I don't think we want to open this up for any security issues at all if we don't need to.

**Comment by lucferbux** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
