### PR TITLE
Add URI connection support for model serving

### PR DESCRIPTION
**Pull request by emilys314**
https://issues.redhat.com/browse/RHOAIENG-13662

[figma](https://www.figma.com/proto/97akqulXiGIGtvxkdPLjMm/Data-connections-enhancement?node-id=2095-320117&t=oqClZqYkjDh3Yp5q-0&scaling=scale-down&content-scaling=fixed&page-id=1135%3A199632&starting-point-node-id=2095%3A320117)

## Description

Add URI model deployments using connection types.

image
image
image

## How Has This Been Tested?

1. Either go to the "Models" details section of a project or open a project via the "Model Serving" on the left nav bar
2. Select single-model serving or multi-model serving (if not set already). Both should be tested.
3. Have a "s3" and a "URI" connection type created
4. Create a new deployment

Example config:
OpenVINO Model Server / onnx - 1
if single serving use URI - https://github.com/emilys314/odh-uri-model/raw/refs/heads/main/fraud.zip
if multi use URI - https://github.com/emilys314/odh-uri-model/raw/refs/heads/main/models/fraud/1/model.onnx
```
curl -X POST -H "content-type: application/json" --data '{"inputs":[{"name":"dense_input","shape":[1,5],"datatype":"FP32","data":[-0.1685591604442391,0.04323738843577523,1.3592881237755046,-0.33397802138714455,-1.3639541744931971]}]}' https://<model-name>-<project-name>.<cluster-url>.com/v2/models/<model-name>/infer
{
    "model_name": "uri",
    "model_version": "1",
    "outputs": [{
            "name": "Identity:0",
            "shape": [1, 1],
            "datatype": "FP32",
            "data": [0.00027472953661344945]
        }]
```

There are many more model deployment variations that can be tested, but.. 

## Test Impact

A simple test added for editing an existing model deployment that is using the URI

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [X] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

@simrandhaliw

### CODE REVIEW

**Comment by christianvogt** [comment]
@simrandhaliw 
I dislike seeing `URI *`. Firstly, when we display fields for connections in our dynamic forms, any read only value does not include the `*` denoting it is required since there's no way to alter the value. Secondly, the radio already indicates this value is a URI.

**Comment by simrandhaliw** [comment]
> @simrandhaliw I dislike seeing `URI *`. Firstly, when we display fields for connections in our dynamic forms, any read only value does not include the `*` denoting it is required since there's no way to alter the value. Secondly, the radio already indicates this value is a URI.

Yes, that does seem redundant. The radio button indicates that the value shown below it is the URI value, so we can remove the 'URI *' header

**Comment by emilys314** [comment]
Removed the "URI *" label in the "Current URI" radio body

**Pull request merged**
