### PR TITLE
[RHOAIENG-2404] Replace simple deprecated PF selects with SimpleSelect

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Towards [RHOAIENG-2404](https://issues.redhat.com/browse/RHOAIENG-2404)

## Description
Updates SimpleDropdownSelect to SimpleSelect using the PF Select component rather than Dropdown. This provides the checkmark indicators for the current selection in the menu items.
Replace simple usages of PF Select component with SimpleSelect.

## How Has This Been Tested?
Manually tested
Updated Cypress tests

## Test Impact
The following components are effected:

- Resources -> Sort type select and sort order select
- Model Serving -> click on a model name: `Time range` and `Refresh interval` select drop downs.
- Data Science Projects -> select a project -> permissions tab:
    Add user -> username selector
    Add group -> group name selector
- Data Science Projects -> select a project -> workbench tab -> create a workbench:
    Image Selection
    Version selection
    Container size
    Environment variables -> Add variable:
      Select environment variable type
      Select environment variable type -> secret -> either -> select one
- Data Science Projects -> Launch Jupyter -> select container size

## Request review criteria:
Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

### CODE REVIEW

**Review by jenny-s51 — COMMENTED** [review]
Changes are looking good @jeff-phillips-18 ! Tested all the Select menus listed in the PR description. 

I noticed the checkmarks aren't getting set in the Select menus under permission settings:
Screenshot 2024-08-08 at 10 13 40 AM

Left another comment below, aside from that LGTM, other menus working as expected.

**Comment by jeff-phillips-18** [comment]
> I noticed the checkmarks aren't getting set in the Select menus under permission settings:

Fixed.

**Review by jenny-s51 — APPROVED** [review]
/lgtm

**Comment by christianvogt** [comment]
Tested all referenced areas to be working.

**Pull request merged**
