### PR TITLE
Update Edit description in project permission dropdown

### LINKED ISSUE #1241: [Bug]: Projects - Improve Permission for "Edit" Text
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When sharing a project with another user, the text would allude you could share "Edit" with them and they will be allowed to edit the project itself... that was a misnomer in text. Since this is not how K8s works, we will just need to change the text.

### Expected Behavior

Modify the text to clarify "components" as that is the first tab.

"View and edit the project components"

Wording provided by UX - @kywalker-rh

### Steps To Reproduce

1. Enable project sharing
2. Go to a project you created
3. Share the permissions with another user -- note the Edit description text in the dropdown

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
Dashboard: v2.10.0
```

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1241 

## Description

It's a one-liner fix, just the text update.

Screenshot 2023-05-17 at 1 36 30 PM

## How Has This Been Tested?

1. Login to the dashboard as an admin user
2. Go to any of the projects
3. Go to the Permissions tab
4. Click on `Add user` and open the dropdown to select the permission, check if the description of the Edit selection is updated

## Test Impact

Text update, N/A.

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

**Review by andrewballantyne — APPROVED** [review]
Kyle's approval is really all that was needed here.

**Pull request merged**
