### PR TITLE
Add "Collapse All" and "Expand All" actions to control bar in topology view

### PR DESCRIPTION
**Pull request by jenny-s51**
JIRA: https://issues.redhat.com/browse/RHOAIENG-7430

## Description

Add "Collapse All" and "Expand All" actions to control bar in topology view.

Screenshot 2024-06-06 at 3 32 22 PM
Screenshot 2024-06-06 at 3 32 34 PM

## How Has This Been Tested?

1. Open a pipeline or run.
2. Click "Collapse All" or "Expand All" action in control bar.
3. Verify that the expand/collapse works as expected.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [x] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
This looks good

/lgtm

waiting on one more review

**Review by DaoDaoNoCode — APPROVED** [review]
Tested and it works well. Just one question, I saw a lot of console print and looks like they are from the PF topology component. Is there a way to silence them or will there be a fix to remove those console messages?

Screenshot 2024-06-07 at 3 51 17 PM

**Review by jenny-s51 — COMMENTED** [review]
Nice catch @DaoDaoNoCode , opened an issue upstream: https://github.com/patternfly/react-topology/issues/217

**Review by Gkrumbach07 — APPROVED** [review]
Second review is good. we can merge

/approve

**Pull request merged**
