### PR TITLE
[RHOAIENG-1107] Storage Class Filter

### PR DESCRIPTION
**Pull request by jpuzz0**
https://issues.redhat.com/browse/RHOAIENG-1107

## Description
Added filter toolbar and pagination to the storage classes table page. Users can filter by display name and/or Openshift class name.

image
image
image

**Demo:** 
https://github.com/user-attachments/assets/6d86fe29-a3c8-46f1-badc-e459dce17123

(cc @xianli123)

## How Has This Been Tested?
1. With the feature flag enabled, visit the storage class table's page; `/storageClasses?devFeatureFlags=disableStorageClasses`
2. Verify pagination exists
3. Verify the toolbar filter exists and matches the design
4. Verify you can filter by both display name and openshift class name
5. Verify empty state when filter yields no results and can reset filters via the action in that empty state ("Clear filters")

## Test Impact
Added catch-all filter cypress test for storage classes

## Request review criteria:
Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by xianli123** [comment]
Thanks @jpuzz0 . Overall, it looks good to me. 
One small change would be that the "S" of "OpenShift" in the placeholder should be a capital letter. 
image

**Comment by jpuzz0** [comment]
> Thanks @jpuzz0 . Overall, it looks good to me. One small change would be that the "S" of "OpenShift" in the placeholder should be a capital letter.

@xianli123 thanks for pointing this out! This is now corrected:
image

**Review by DaoDaoNoCode — APPROVED** [review]
Tested, works well
/lgtm

**Review by Gkrumbach07 — APPROVED** [review]

**Comment by xianli123** [comment]
Thanks @jpuzz0. LGTM!

**Pull request merged**
