### PR TITLE
Update 'Resource name' fields to meet UX guidelines: Serving Runtimes

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Towards [RHOAIENG-14746](https://issues.redhat.com/browse/RHOAIENG-14746)

## Description
Updates the create/edit dialog for Model Servers to use the common `K8sNameDescriptionField` component in order to meet current UX guidelines.

### Create
image

### Edit resource name popover
image

### Create editing Resource name
image

### Edit
image

## How Has This Been Tested?
- Navigate to a project this model servers and select the `Models` tab
  - Select `Add model server`
  - Enter the name for the new model server.
  - View the resource name via the `Edit resource name` link.
  - Change the resource name to something invalid (ie. contains a space)
  - Verify the submit button is disabled
  - Change the resource name to something valid
  - Verify the submit button is enabled
  - Save the profile.
  - Verify the profile is created with the correct Display name and Resource Name.
- Navigate to a project this model servers and select the `Models` tab
  - Select the kebab for an existing model server and choose `Edit`
  - Update the Name field
  - Notice the resource name is not editable
  - Save the model server.
  - Verify the model server is updated with the correct Display name.

## Test Impact
Updated unit tests for new fields

## Request review criteria:
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

/cc @simrandhaliw

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
@manosnoam Updated `data-testid` for the accelerator profile dialog Name field was updated from `serving-runtime-name-input` to `serving-runtime-name`

**Review by jenny-s51 — COMMENTED** [review]
These updates are looking great, @jeff-phillips-18 ! I noticed one small issue: when adding a model server and customizing the resource name, it's expected that this custom resource name is saved initially. 

However when you toggle "Edit model server" from the actions menu the custom name is not retained and the resource name just matches the model server name.

**Comment by jeff-phillips-18** [comment]
> the custom name is not retained and the resource name just matches the model server name.

@jenny-s51 Fixed.

**Review by jenny-s51 — COMMENTED** [review]
Great work on the resource name fix, @jeff-phillips-18 ! Thank you for making that update. Just a few things I wanted to check in on:

- For [ResourceNameDefinitionTooltip](https://github.com/opendatahub-io/odh-dashboard/pull/3443/files#diff-88024c022aebdd76da18537d9d70ea4ccce81af9e4ce77ea4990514c974cb1f2R96), the tooltip text currently differs a bit from what’s outlined in the [guidelines](https://docs.google.com/document/d/1hiIf4bE06cUcI5xU9-n6i3vt6h_dVP4haI0b2gf-qac/edit?tab=t.0). Do we want to stick with the guideline here, or use the current text?

    Screenshot 2024-11-14 at 2 22 57 PM

- For long server names, seems like the resource name is currently matching the full input, but the guidelines suggest truncating to the first 30 characters.
     Screenshot 2024-11-14 at 2 07 30 PM
- For the table, would it make sense to truncate long names there as well to maintain a cleaner look? 
    Screenshot 2024-11-14 at 2 14 01 PM

**Comment by jeff-phillips-18** [comment]
> * For long server names, the resource name is currently matching the full input, but the guidelines suggest truncating to the first 30 characters.

@jenny-s51 The guidelines say `If the resource name has a limit on the number of characters`, the limit here is 253 I believe.

**Comment by jeff-phillips-18** [comment]
> * For [ResourceNameDefinitionTooltip](https://github.com/opendatahub-io/odh-dashboard/pull/3443/files#diff-88024c022aebdd76da18537d9d70ea4ccce81af9e4ce77ea4990514c974cb1f2R96), the tooltip text currently differs a bit from what’s outlined in the [guidelines](https://docs.google.com/document/d/1hiIf4bE06cUcI5xU9-n6i3vt6h_dVP4haI0b2gf-qac/edit?tab=t.0).

@jenny-s51 I have updated the text. See the added screenshot in the PR description

**Pull request merged**
