### PR TITLE
Modify help text under for image version selection

### LINKED ISSUE #1444: [Bug]: Modify help text under for image version selection
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Help text for NB image version selection field in 'create workbench' screen isn't clear.

Help text under field says "Hover an option to learn more information about the package."

### Expected Behavior

The help text displays information about the packages included in the image versions. I think the text could be modified to be clearer: "Hover an option to learn more information about the packages included."

### Steps To Reproduce

1. Under a project, click 'create workbench'. 
2. Select an image under 'Image selection'.
3. Note text under 'Version selection' field.

### Workaround (if any)

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by manaswinidas**
Fixes #1444 

## Description

Refer to #1444 
Screenshot 2023-06-28 at 9 24 50 PM

## How Has This Been Tested?

1. Under a project, click 'create workbench'.
2. Select an image under 'Image selection'.
3. Note text under 'Version selection' field.

## Request review criteria:

- [X] The commits have meaningful messages (squashes happen on merge by the bot).
- [X] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by lucferbux** [comment]
@DaoDaoNoCode @Gkrumbach07 @pnaik1 @uidoyen can someone take a look at this pr? I think we can manage to get it merge asap.

**Comment by pnaik1** [comment]
@lucferbux  yeah i will have a look

**Comment by pnaik1** [comment]
helpertext
look good to me

**Pull request merged**
