### PR TITLE
2.1 hotfix bugs

### PR DESCRIPTION
**Pull request by andrewballantyne**
Addressing hot fix bugs against our 2.1 version of the ODH Dashboard.

Directly for the RHODS 1.16 rebuild.

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

Tested and it works with the same testsuite we've been using, new health endpoint seems to be returning as expected.

**Comment by LaVLaS** [comment]
@andrewballantyne Are the changes from #543 required for this hotfix?

**Comment by andrewballantyne** [comment]
> @andrewballantyne Are the changes from #543 required for this hotfix?

I believe so -- I thought it was the problem with the build which is what Chris implemented to fix it.

**Comment by LaVLaS** [comment]
> > @andrewballantyne Are the changes from #543 required for this hotfix?
> 
> I believe so -- I thought it was the problem with the build which is what Chris implemented to fix it.

Ignore my comment I missed that you pulled that commit in before my comment

**Comment by andrewballantyne** [comment]
Downstream effort was merged. Merging effort https://github.com/red-hat-data-services/odh-dashboard/pull/237

**Pull request merged**
