### PR TITLE
Remove cypress suppression of uncaught exceptions

### PR DESCRIPTION
**Pull request by manaswinidas**
Closes: https://issues.redhat.com/browse/RHOAIENG-10715
Closes: https://issues.redhat.com/browse/RHOAIENG-7565
Closes: https://issues.redhat.com/browse/RHOAIENG-11444
Closes: https://issues.redhat.com/browse/RHOAIENG-11847

## Description

These snippets had been introduced to work around a Patternfly bug with `ExpandableSection` [https://github.com/patternfly/patternfly-react/issues/10410](https://github.com/patternfly/patternfly-react/issues/10410) This has been fixed - removing these suppressions because they can hide other uncaught exceptions.

## How Has This Been Tested?

- Run Cypress test files `modelVersionArchive.cy.ts` and `registeredModelArchive.cy.ts` and check whether they run fine.

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by mturley** [comment]
@manaswinidas it looks like we're still getting the exception - I think we need to upgrade PatternFly to pull in the fix.

According to this PR it was released in `@patternfly/react-core@5.4.0` but we're still on 5.3.3.

**Comment by mturley** [comment]
good question... looking into it

**Comment by mturley** [comment]
I'm confused by the test failing on `"after each" hook for "Restore from archive version details"`, I don't see an `afterEach` in there anywhere

**Comment by mturley** [comment]
The tests are passing for me locally too... I think maybe there's a rendering race condition and the exception isn't necessarily always thrown. Maybe we can just upgrade PF and make sure it passes and that's sufficient.

**Comment by manaswinidas** [comment]
@mturley `@patternfly/react-core@5.4.0` is still in pre-release according to [npm versions history](https://www.npmjs.com/package/@patternfly/react-core?activeTab=versions)

**Comment by mturley** [comment]
/hold
holding this until PatternFly releases 5.4.0 and we can upgrade to that version in this PR. The Jira is blocked until that happens - The PatternFly team says the release is expected today. If there are further delays we'll need to roll over the issue to the next sprint.

**Comment by mturley** [comment]
Once PF releases and we unblock this, let's make sure to also remove the newly introduced instance of this in https://github.com/opendatahub-io/odh-dashboard/pull/3116/files#diff-cfd373dd2cc4bd02bbf6aa15837b2b82aed88e0ef783079334d738c8b22d6ceaR206-R208

**Review by mturley — APPROVED** [review]
Thanks @manaswinidas ! This was a fun one huh

**Pull request merged**
