### PR TITLE
Bump PatternFly version

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**

### CODE REVIEW

**Review by dlabaj — CHANGES_REQUESTED** [review]
Can you fix the snapshots?  Otherwise looks good.

**Comment by DaoDaoNoCode** [comment]
@dlabaj I don't know what happened to my codebase, I cannot use the `jest` CLI command.

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by andrewballantyne** [comment]
Surely there has been a release of Patternfly in the last 3 months from when this PR was created.

@DaoDaoNoCode can we update the deps here?

**Comment by DaoDaoNoCode** [comment]
@andrewballantyne Sure, I will do this later after some other features are merged.

**Comment by andrewballantyne** [comment]
This PR is old. If we want to do this, we should log a ticket, associate it to a PR and just start over on the effort. So much has changed since this was open and we don't really need to try and stretch this one into the present.

**Pull request closed without merging**
