### PR TITLE
Create dedicated OAuthclient

### PR DESCRIPTION
**Pull request by samuelvl**
## Description
Fix https://github.com/opendatahub-io/odh-dashboard/issues/479

## How Has This Been Tested?
Install the `opendatahub-operator` and patch the CSV image:

``` shell
$ oc edit csv opendatahub-operator.v1.3.0 -n openshift-operator
...
326                 image: quay.io/opendatahub/opendatahub-operator:v1.3.0 -> quay.io/vhire/opendatahub-operator:testoauth
...
```

Edit the `.env` file to use the following image:

```
IMAGE_REPOSITORY=quay.io/samuvl/odh-dashboard:oauth-client
```

Run `make deploy` and wait until the dashboard is deployed and running:

```
$ oc get pods -l app=odh-dashboard -n opendatahub
NAME                             READY   STATUS    RESTARTS   AGE
odh-dashboard-5fbc469d8c-6j7dj   2/2     Running   0          4m9s
odh-dashboard-5fbc469d8c-dbf5w   2/2     Running   0          4m9s
odh-dashboard-5fbc469d8c-pcvpb   2/2     Running   0          4m9s
odh-dashboard-5fbc469d8c-rrtws   2/2     Running   0          4m9s
odh-dashboard-5fbc469d8c-w2lgz   2/2     Running   0          4m9s
```

Verify the `OAuthClient` object is created with the correct information:

```yaml
$ oc get oauthclient dashboard-oauth-client -o yaml             
apiVersion: oauth.openshift.io/v1
grantMethod: auto
kind: OAuthClient
metadata:
  creationTimestamp: "2022-10-24T09:06:00Z"
  name: dashboard-oauth-client
  resourceVersion: "46725569"
  uid: 251c4c25-c123-4eaf-bc1a-1b96e07a5b9e
redirectURIs:
- https://odh-dashboard-opendatahub.apps.samuvl-odh.mydomain.com
secret: jPlOar1OaoWWiVWoDgDRElvpytyGMnf1
```

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by samuelvl** [comment]
Draft until opendatahub-operator 1.4 is released to include https://github.com/opendatahub-io/opendatahub-operator/pull/177

**Comment by andrewballantyne** [comment]
@samuelvl I think this looks to fix this one too -- no? https://github.com/opendatahub-io/odh-dashboard/issues/337

**Comment by samuelvl** [comment]
@andrewballantyne Correct, operator 1.4 release will allow me to mark both PRs as ready.

**Comment by andrewballantyne** [comment]
> @andrewballantyne Correct, operator 1.4 release will allow me to mark both PRs as ready.

Oh I see -- so this one PR won't handle both -- ah okay, thanks for the update.

**Review by andrewballantyne — APPROVED** [review]
/hold

**Review by cfchase — APPROVED** [review]
/lgtm

**Pull request merged**
