### PR TITLE
Remove provider column from Data connection section

### PR DESCRIPTION
**Pull request by manaswinidas**
Closes: https://issues.redhat.com/browse/RHOAIENG-1162

## Description

Removes Provider column from Data Connection section on Projects page

Screenshot 2024-02-16 at 7 05 24 PM

## How Has This Been Tested?

1. Go to any Project and check the Data connection section. You should not see the "Provider" column

## Test Impact

Removed all test related to the "Provider" column

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [X] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by manaswinidas** [comment]
@kywalker-rh can you have a look at the screenshots?

**Review by dpanshug — APPROVED** [review]
/lgtm

**Comment by manaswinidas** [comment]
@xianli123 can you have a look at the screenshots in the PR description?

**Review by lucferbux — APPROVED** [review]
/lgtm

**Pull request merged**
