### PR TITLE
co-locate unit tests with their target source

### PR DESCRIPTION
**Pull request by christianvogt**
## Description

Move unit tests into `__tests__` directory co-located adjacent to their target source files.

## How Has This Been Tested?

Ran `npm run test:unit` in the `frontend` dir:

image

## Test Impact

None.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by manaswinidas — COMMENTED** [review]
Do we have to run `npm run test:unit` or `npm run test:jest`? Tested both. They give the same results. 
Can you please update the PR description? I don't think we have such a script `npm run test:junit`.

**Comment by christianvogt** [comment]
@manaswinidas fixed the typo in the description for `npm run test:unit` and also mentioned it's for the `frontend` dir.

**Review by DaoDaoNoCode — APPROVED** [review]
/lgtm
Run the command, works fine

**Review by manaswinidas — APPROVED** [review]
/lgtm

Tested. Works fine.

**Pull request merged**
