### PR TITLE
add dynamic namespace to delegate-url oauth arg

### LINKED ISSUE #1045: [Bug]: Unable to authenticate to odh-dashboard with Service Account
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Related to this issue:

https://github.com/opendatahub-io/odh-manifests/issues/757

If a Service Account is granted a narrow scope to get routes in the specific namespace that the opendatahub instance is deployed it will be unable to authenticate to with the OAuth Proxy instance. With the current --openshift-delegate-url arg the Service Account must have cluster level permissions to view all routes on the cluster.

When attempting to authenticated via a Bearer Token with a service account, the request is rejected with a 403 error message.

### Expected Behavior

Service Accounts should be able to authenticate via Bearer Token by only granting view permissions to the routes that the odh-dashboard is deployed to and not cluster level view permissions.

### Steps To Reproduce

1. Install ODH with a standard kfdef in a namespace called `opendatahub`
2. Create a test service account:
```
oc create sa test-connection
```
3. Grant permissions to the service account:
```
oc policy add-role-to-user view system:serviceaccount:opendatahub:test-connection
```
4. Verify SA has permissions to list service:
```
TOKEN=$(oc create token test-connection -n opendatahub)
oc login --token=${TOKEN}
oc get services odh-dashboard -n opendatahub
```
5.  Attempt to authenticate to OAuth
```
URL="https://$(oc get routes odh-dashboard -n opendatahub -o jsonpath='{.spec.host}' )"
curl --location --request GET $URL \
--header "Authorization: Bearer ${TOKEN}" -I
```

Request will return a 403 error message.

### Workaround (if any)

Grant the service account cluster level view permissions.

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

```yml
1.4.2 standard kfdef
```

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by strangiato**
Closes #1045 

## Description
Resolve issue with Service Accounts being unable to authenticate to the dashboard without cluster scope permissions

## How Has This Been Tested?
Deployed kfdef manually and followed reproducability instructions in #1045

1. Install ODH with a kfdef in a namespace called `opendatahub` with the following manifests url:

```
  repos:
    - name: manifests
      uri: >-
        https://github.com/strangiato/odh-manifests/tarball/dashboard-oauth-delegate-url-fix
```

2. Create a test service account:
```
oc create sa test-connection
```
3. Grant permissions to the service account:
```
oc policy add-role-to-user view system:serviceaccount:opendatahub:test-connection
```
4. Verify SA has permissions to list service:
```
TOKEN=$(oc create token test-connection -n opendatahub)
oc login --token=${TOKEN}
oc get services odh-dashboard -n opendatahub
```
5.  Attempt to authenticate to OAuth
```
URL="https://$(oc get routes odh-dashboard -n opendatahub -o jsonpath='{.spec.host}' )"
curl --location --request GET $URL \
--header "Authorization: Bearer ${TOKEN}" -I
```

Response will return a 200 instead of a 403.

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [N/A] Included any necessary screenshots or gifs if it was a UI change.
- [N/A] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by lucferbux** [comment]
I've managed to replicate the scenario. Before applying the changes:

```bash
🔋 85% ❯ URL="https://$(oc get routes odh-dashboard -n opendatahub -o jsonpath='{.spec.host}' )"
curl -k --location --request GET $URL \
--header "Authorization: Bearer ${TOKEN}" -I
HTTP/1.1 403 Forbidden
set-cookie: _oauth_proxy=; Path=/; Domain=odh-dashboard-opendatahub.apps.lferrnan-dv.dev.datahub.redhat.com; Expires=Wed, 29 Mar 2023 09:43:20 GMT; HttpOnly; Secure
date: Wed, 29 Mar 2023 10:43:20 GMT
content-type: text/html; charset=utf-8
transfer-encoding: chunked
strict-transport-security: max-age=31536000;includeSubDomains;preload
set-cookie: 8501a734cf1ca23d6de5de397744693d=c93503a240ee7bfc9d602ebf831058e0; path=/; HttpOnly; Secure; SameSite=None
```

After applying the changes

```bash
🔋 83% ❯ URL="https://$(oc get routes odh-dashboard -n opendatahub -o jsonpath='{.spec.host}' )"
curl -k --location --request GET $URL \
--header "Authorization: Bearer ${TOKEN}" -I
HTTP/1.1 200 OK
accept-ranges: bytes
cache-control: public, max-age=0
content-length: 450
content-type: text/html; charset=UTF-8
date: Wed, 29 Mar 2023 10:51:21 GMT
etag: W/"1c2-1872b1f5f28"
gap-auth: system:serviceaccount:opendatahub:test-connection@cluster.local
gap-upstream-address: localhost:8080
last-modified: Wed, 29 Mar 2023 02:08:09 GMT
strict-transport-security: max-age=31536000;includeSubDomains;preload
set-cookie: 8501a734cf1ca23d6de5de397744693d=c99237250d54abc5608ef1849249f6b0; path=/; HttpOnly; Secure; SameSite=None
```

My only concern is, @strangiato is this needed for development purposes too? If so, please add these changes to the `Deployment` file in the `base` directory. The auth overlay is used for deployment, whilst `make deploy` in development omit these changes.

**Comment by strangiato** [comment]
Good catch @lucferbux.  I didn't realize the oauth-proxy was setup in the base as well.  I went ahead and added the same changes there.

**Comment by lucferbux** [comment]
Great, thanks a lot!

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by shalberd** [comment]
Very nice work, you mention a ClusterRolebinding not being necessary. Would a rolebinding at namespace-level for the ServiceAccount odh-dashboard, instead a a ClusterRoleBinding be sufficient, too? I am talking about the RBAC-related yamls here https://github.com/opendatahub-io/odh-dashboard/tree/main/manifests/base vs here, too, at odh-manifests.

**Comment by strangiato** [comment]
@shalberd This change probably doesn't impact the odh-dashboard service account.  ODH-Dashboard will always need things like [system:auth-delegator](https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/base/auth-delegator.clusterrolebinding.yaml) if you are using the `--openshift-delegation-url` feature of the oauth-proxy.  The rest of the permissions are based on things that the odh-dashboard is expected to be able to access in the cluster.

This change is intended to enable other service accounts that that are probably running other applications in the cluster that may need to make a REST call to an API to an API endpoint that is provided by odh-dashboard.

In my example I show the `test-connection` service account just attempting to curl the home page which is probably not a functionally useful example but a very simple test.  If you look at the html for the 403 response you will notice it is returning the "Login with openshift" page the user normally sees when they attempt to access the dashboard.  With the fix it returns the home page instead.  The "work around" is that I can grant `test-connection` cluster level permissions to list all services on the entire cluster, and that service account is able to authenticate, but that is probably way more permissions than I really want to give the service account.

Another way to look at it is in the current setup the `test-connection` service account needs to be able to run:

```
oc get services odh-dashboard --all-namespaces
```

And the fix it only needs to be able to run:

```
oc get services odh-dashboard -n <namespace-where-odh-is-installed>
```

I anticipate that this capability will become more important as the kubeflow-pipelines UI gets integrated into the odh-dashboard.  The piece that I anticipate will be needed is the API endpoints that the current kubeflow-pipelines UI exposes for allowing to utilize the python `kfp_tekton.client()` to do things like upload pipelines, trigger runs, etc.  In some other issues I have seen some discussion about odh-dashboard proxying these APIs so my assumption is that I will need to be able to go through odh-dashboard to access these APIs in the future.

But there could be any number of reasons outside of the use case above that you would want a service account to be able to authenticate to the odh-dashbaord.

**Comment by shalberd** [comment]
> The rest of the permissions are based on things that the odh-dashboard is expected to be able to access in the cluster.

Ah, of course, yes, due to the Management functionality, e.g. namespace creation in ODH dashboard for Data Science Projects, for example.

> there could be any number of reasons outside of the use case above that you would want a service account to be able to authenticate to the odh-dashboard

Very nicely explained, and now the connection to DS pipelines functionality is more clear to me. 

Thank you for the great response.

**Review by andrewballantyne — APPROVED** [review]

**Pull request merged**
