### PR TITLE
Fix for input not allowing blank spaces.:

### PR DESCRIPTION
**Pull request by dlabaj**
Fix to allow a user to enter an empty string.

https://user-images.githubusercontent.com/6126356/158695015-14ffe643-580b-40aa-a444-c66692f9fde2.mov

### CODE REVIEW

**Comment by cfchase** [comment]
Functionality is a little weird changing the value while a user types.  For instance, I can't type 1.5, however I an type in 15 and then put in a ".' for 1.5 afterwards.  Maybe it'd be easier if we validate onBlur and then only submit if it's correct or show a validation error?

**Comment by cfchase** [comment]
Functionality is a little weird changing the value while a user types.  For instance, I can't type 1.5, however I an type in 15 and then put in a ".' for 1.5 afterwards.  Maybe it'd be easier if we validate onBlur and then only submit if it's correct or show a validation error?

**Review by DaoDaoNoCode — COMMENTED** [review]
Looks good to me, I have only one question. If the user inputs an empty string, they will get 1 instead, could it be set to the default value(20) if the user inputs an empty string?

**Comment by dlabaj** [comment]
> Functionality is a little weird changing the value while a user types. For instance, I can't type 1.5, however I an type in 15 and then put in a ".' for 1.5 afterwards. Maybe it'd be easier if we validate onBlur and then only submit if it's correct or show a validation error?

It shouldn't let you that . in between 1.5 the regex needs to be updated.

**Comment by cfchase** [comment]
> > Functionality is a little weird changing the value while a user types. For instance, I can't type 1.5, however I an type in 15 and then put in a ".' for 1.5 afterwards. Maybe it'd be easier if we validate onBlur and then only submit if it's correct or show a validation error?
> 
> It shouldn't let you that . in between 1.5 the regex needs to be updated.

If the intent is to only allow integers, would setting `type="number" min="1" max="1234"` be easier than a regex?

**Comment by dlabaj** [comment]
> > > Functionality is a little weird changing the value while a user types. For instance, I can't type 1.5, however I an type in 15 and then put in a ".' for 1.5 afterwards. Maybe it'd be easier if we validate onBlur and then only submit if it's correct or show a validation error?
> > 
> > 
> > It shouldn't let you that . in between 1.5 the regex needs to be updated.
> 
> If the intent is to only allow integers, would setting `type="number" min="1" max="1234"` be easier than a regex?
> 
> edit: nevermind, that (or the Patternfly [NumberInput](https://www.patternfly.org/v4/components/number-input)) would also allow decimals. I kind of like the decimals, though. I guess we don't want that for some reason? setting a PV to 1.2Gi is usually allowed

yeah in the requirements for this feature we are not allowing decimals.

**Comment by dlabaj** [comment]
> Looks good to me, I have only one question. If the user inputs an empty string, they will get 1 instead, could it be set to the default value(20) if the user inputs an empty string?

I changed it so it won't save anything if it's empty.

**Review by crobby — APPROVED** [review]
lgtm

**Pull request merged**
