### PR TITLE
Add support for npm v9

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Closes: #1136 

### 1 - Image
You can either create a new image:

1. Switch to `bump-npm-version`
2. Add your quay repo and the tag that you want in `IMAGE_REPOSITORY`
3. Create a new build with `make build`
4. Push it to the selected repo with `make push`

Or use an existing image

1. Change `IMAGE_REPOSITORY` in your `.env.local` file to `IMAGE_REPOSITORY=quay.io/opendatahub/odh-dashboard:pr-1392`

### 2 - Deploy
You can either deploy this in your existing deployment or create a new one.

To use your existing deployment:

1. Scale down the operator deployment in `openshift-operators` namespace to avoid reconciliation
2. Go to the dashboard deployment
3. Change the image in the dashboard deployment to  your recently build image or `quay.io/opendatahub/odh-dashboard:pr-1392`

Screenshot 2023-06-29 at 17 01 33

Use the dashboard deployment:

1. Be sure to delete the kfdef with the dashboard deployment
2. Now in the dashboard repo, run `make deploy`

### 3 - Outcome

You need to be able to launch the odhDashboard and the Pods should not be constantly restarting due to some init errors.

## Test Impact

Estructural change, you can test it installing `quay.io/lferrnan/odh-dashboard:bump-npm-version`

## Request review criteria:

- [X] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by lucferbux** [comment]
@LaVLaS @andrewballantyne The changes are working just fine downstream, should we test this with the openshift CI just in case?

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
Need to update the readme requirements too.

https://github.com/opendatahub-io/odh-dashboard/blob/main/README.md#requirements

**Comment by LaVLaS** [comment]
> @LaVLaS @andrewballantyne The changes are working just fine downstream, should we test this with the openshift CI just in case?

If testing in openshift-ci is a reference to #1123 then I think an local test of the prebuilt image should be sufficient as a smoke test since there were scenarios where the error was reproducible locally but not in openshift-ci

**Comment by lucferbux** [comment]
> quay.io/lferrnan/odh-dashboard:bump-npm-version

Ok, so I've tested the changes here: quay.io/lferrnan/odh-dashboard:bump-npm-version and it seems to be working locally just fine, I'm gonna test right now to install `quay.io/opendatahub/odh-dashboard:pr-1392` just to verify if it's working, I'll update both the changes and the status of those tests asap

**Comment by lucferbux** [comment]
Tested and working with `quay.io/opendatahub/odh-dashboard:pr-1392` it should be ready to go! 

@Gkrumbach07 @DaoDaoNoCode @andrewballantyne @LaVLaS We can check this and merge it now

**Comment by andrewballantyne** [comment]
> Tested and working with `quay.io/opendatahub/odh-dashboard:pr-1392` it should be ready to go!
> 
> @Gkrumbach07 @DaoDaoNoCode @andrewballantyne @LaVLaS We can check this and merge it now

As far as I recall -- this has never been a problem upstream in ODH -- we have only ever had issues with the build system in RHODS due to the artifacts it is built with.

**Comment by lucferbux** [comment]
> > Tested and working with `quay.io/opendatahub/odh-dashboard:pr-1392` it should be ready to go!
> > @Gkrumbach07 @DaoDaoNoCode @andrewballantyne @LaVLaS We can check this and merge it now
> 
> As far as I recall -- this has never been a problem upstream in ODH -- we have only ever had issues with the build system in RHODS due to the artifacts it is built with.

@andrewballantyne  We had a problem with the latest ubi8 image, mainly due to caching issues in the odh CI/CD pipeline, that's why we had some releases blocked a few weeks ago.

I've tested both a local image and the one built by openshift, it should work fine now.

**Review by manaswinidas — APPROVED** [review]

**Review by andrewballantyne — APPROVED** [review]

**Pull request merged**
