### PR TITLE
Revamp add server button and add tooltip

### LINKED ISSUE #1579: Revamp "Add server" button
### Feature description

Revamp the button in DSProject to Add a model server, the main changes are:

- Change the display text from `Add server` to `Add model server`
- Add a tooltip to display on hover
- Add a tooltip description: A model server specifies resources available for use by one or more supported models, and includes a serving runtime.

### Mockups
https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/dgj4pn2

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1579 

## Description

Change the name to `Add model server` and add a tooltip on hover.

Screenshot 2023-09-29 at 12 11 15 PM

## How Has This Been Tested?

1. Go to data science project
2. Check if the button is `Add model server` now, but not `Add server`
3. Hover the button to see the tooltip

## Test Impact

N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@vconzola Can you please check the visual changes here?

**Comment by vconzola** [comment]
@DaoDaoNoCode Why did this get assigned to me? 🙀

**Comment by DaoDaoNoCode** [comment]
@vconzola Haha this is an openshift-ci thing... As long as you use `/lgtm` command 😉

**Comment by vconzola** [comment]
@DaoDaoNoCode What does it mean that it's assigned to me? Should I not have used "/"? Can you make it go away?

**Comment by DaoDaoNoCode** [comment]
@vconzola It doesn't matter 😛 Just go with it, you don't need to do anything.

**Comment by andrewballantyne** [comment]
/hold

@DaoDaoNoCode this needs to not merge into main. It's a story issue. Stories merge to feature branches.

**Comment by DaoDaoNoCode** [comment]
@andrewballantyne Ah, looks like I have some other PRs that need to be redirected too.

**Comment by DaoDaoNoCode** [comment]
/unhold
Changed the target to the feature branch.

**Pull request merged**
