### PR TITLE
Edge pipeline topology

### PR DESCRIPTION
**Pull request by dpanshug**
Closes: [RHOAIENG-238](https://issues.redhat.com/browse/RHOAIENG-238)  #2250

## Description
Added Edge pipeline topology views

Pipeline page

image

Pipeline page YAML

image

Pipeline run page

image

@vconzola 

## How Has This Been Tested?
Create pipeline and pipelineRun from [here](https://github.com/opendatahub-io/ai-edge/blob/9a3c0e48fa3c7395be3ccdfc89575c0088b9841a/pipelines/tekton/aiedge-e2e/aiedge-e2e.pipeline.yaml)

Redirect to `http://localhost:4010/edgePipelines/pipeline/view/aiedge-e2e` for pipeline topology page
and to `http://localhost:4010/edgePipelines/pipelineRun/view/<pipelineRunName>` for pipeline run topology page

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by vconzola** [comment]
LGTM. I assume all the page controls at the bottom work, and the YAML view is available? I can't see those.

**Comment by dpanshug** [comment]
> LGTM. I assume all the page controls at the bottom work, and the YAML view is available? I can't see those.

@vconzola screenshot for YAML page added, and the controls are also working fine same as in DS pipelines, no change on that part.

**Comment by Gkrumbach07** [comment]
tested and works.

**Comment by Gkrumbach07** [comment]
tests pass now. merging

**Pull request merged**
