### PR TITLE
rerender only the schedule which got toggled

### PR DESCRIPTION
**Pull request by pnaik1**
https://issues.redhat.com/browse/RHOAIENG-11858

## Description
ggle one of the schedules to enable or disable it, and that should only trigger and re-render of that particular schedule

## How Has This Been Tested?

1. Use a pipeline version to create some schedules
2. View schedules for that pipeline version
3. Try to toggle the "Status" column for any row
Check if  It will only trigger re-render of the current row and re-fetch the current schedule

## Test Impact
N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by DaoDaoNoCode — APPROVED** [review]
Tested, works well
/lgtm

**Comment by Gkrumbach07** [comment]
Ok i think this is a bit more complicated then it should be. The tables data fetching hook can return a refresh function which only refreshes the recurring run data and not all data. and it will still not force update the whole thing

this is the old (in main now)

https://github.com/user-attachments/assets/19c0c008-a7ab-4c75-884c-ad6c857bc1ee

This is the new

https://github.com/user-attachments/assets/9d93494d-2fdb-4ce1-8455-5e527ff85b60

```diff
diff --git a/frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx b/frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx
index d8fc9e75c..50036f023 100644
--- a/frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx
+++ b/frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx
@@ -18,7 +18,7 @@ import PipelineRecurringRunTableToolbar from './PipelineRecurringRunTableToolbar
 
 type PipelineRecurringRunTableProps = {
   recurringRuns: PipelineRecurringRunKFv2[];
-  refreshSingleRecurringRun: (recurringRun: PipelineRecurringRunKFv2) => void;
+  refresh: () => void;
   loading?: boolean;
   totalSize: number;
   page: number;
@@ -34,7 +34,7 @@ type PipelineRecurringRunTableProps = {
 
 const PipelineRecurringRunTable: React.FC<PipelineRecurringRunTableProps> = ({
   recurringRuns,
-  refreshSingleRecurringRun,
+  refresh,
   loading,
   totalSize,
   page,
@@ -124,7 +124,7 @@ const PipelineRecurringRunTable: React.FC<PipelineRecurringRunTableProps> = ({
         rowRenderer={(recurringRun) => (
           <PipelineRecurringRunTableRow
             key={recurringRun.recurring_run_id}
-            refreshSingleRecurringRun={refreshSingleRecurringRun}
+            refresh={refresh}
             isChecked={isSelected(recurringRun.recurring_run_id)}
             onToggleCheck={() => toggleSelection(recurringRun.recurring_run_id)}
             onDelete={() => setDeleteResources([recurringRun])}
diff --git a/frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTableRow.tsx b/frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTableRow.tsx
index 1787dbecc..c08e61c50 100644
--- a/frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTableRow.tsx
+++ b/frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTableRow.tsx
@@ -19,7 +19,7 @@ import useExperimentById from '~/concepts/pipelines/apiHooks/useExperimentById';
 
 type PipelineRecurringRunTableRowProps = {
   isChecked: boolean;
-  refreshSingleRecurringRun: (recurringRun: PipelineRecurringRunKFv2) => void;
+  refresh: () => void;
   onToggleCheck: () => void;
   onDelete: () => void;
   recurringRun: PipelineRecurringRunKFv2;
@@ -27,7 +27,7 @@ type PipelineRecurringRunTableRowProps = {
 
 const PipelineRecurringRunTableRow: React.FC<PipelineRecurringRunTableRowProps> = ({
   isChecked,
-  refreshSingleRecurringRun,
+  refresh,
   onToggleCheck,
   onDelete,
   recurringRun,
@@ -100,7 +100,7 @@ const PipelineRecurringRunTableRow: React.FC<PipelineRecurringRunTableRowProps>
           onToggle={(checked) =>
             api
               .updatePipelineRecurringRun({}, recurringRun.recurring_run_id, checked)
-              .then(() => refreshSingleRecurringRun(recurringRun))
+              .then(() => refresh())
           }
         />
       </Td>
diff --git a/frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx b/frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx
index 2639db627..350416ae4 100644
--- a/frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx
+++ b/frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx
@@ -16,32 +16,15 @@ import CreateScheduleButton from '~/pages/pipelines/global/runs/CreateScheduleBu
 import { useContextExperimentArchived as useIsExperimentArchived } from '~/pages/pipelines/global/experiments/ExperimentContext';
 import { usePipelineRecurringRunsTable } from '~/concepts/pipelines/content/tables/pipelineRecurringRun/usePipelineRecurringRunTable';
 import PipelineRecurringRunTable from '~/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable';
-import { PipelineRecurringRunKFv2 } from '~/concepts/pipelines/kfTypes';
-import { usePipelinesAPI } from '~/concepts/pipelines/context';
 
 const ScheduledRuns: React.FC = () => {
   const { experimentId, pipelineVersionId } = useParams();
-  const [[{ items: recurringRuns, totalSize }, loaded, error], { initialLoaded, ...tableProps }] =
-    usePipelineRecurringRunsTable({ experimentId, pipelineVersionId });
+  const [
+    [{ items: recurringRuns, totalSize }, loaded, error, refresh],
+    { initialLoaded, ...tableProps },
+  ] = usePipelineRecurringRunsTable({ experimentId, pipelineVersionId });
   const isExperimentArchived = useIsExperimentArchived();
 
-  const { api } = usePipelinesAPI();
-  const [updatedRecurringRuns, setUpdatedRecurringRuns] = React.useState<
-    PipelineRecurringRunKFv2[]
-  >([]);
-
-  React.useEffect(() => setUpdatedRecurringRuns(recurringRuns), [recurringRuns]);
-
-  const refreshSingleRecurringRun = (recurringRun: PipelineRecurringRunKFv2) => {
-    api.getPipelineRecurringRun({}, recurringRun.recurring_run_id).then((newState) => {
-      setUpdatedRecurringRuns((prevState) =>
-        prevState.map((run) =>
-          run.recurring_run_id === recurringRun.recurring_run_id ? newState : run,
-        ),
-      );
-    });
-  };
-
   if (error) {
     return (
       <Bullseye>
@@ -92,8 +75,8 @@ const ScheduledRuns: React.FC = () => {
 
   return (
     <PipelineRecurringRunTable
-      refreshSingleRecurringRun={refreshSingleRecurringRun}
-      recurringRuns={updatedRecurringRuns}
+      refresh={refresh}
+      recurringRuns={recurringRuns}
       loading={!loaded}
       totalSize={totalSize}
       {...tableProps}
```

**Comment by pnaik1** [comment]
@Gkrumbach07, I observed the `refresh` coming from tables data fetching hook, However, I noted the mention in [issue-11858](https://issues.redhat.com/browse/RHOAIENG-11858#:~:text=It%20will%20only%20trigger%20re%2Drender%20of%20the%20current%20row%20and%20re%2Dfetch%20the%20current%20schedule) regarding refreshing and re-fetching  only the updated recurring runs , rather than all of the recurring runs, I opted for this approach, but I am open to making changes, Please let me know your thoughts here

**Comment by Gkrumbach07** [comment]
> I did notice the refresh coming from tables data fetching hook, However, I noted the mention in [issue-11858](https://issues.redhat.com/browse/RHOAIENG-11858#:~:text=It%20will%20only%20trigger%20re%2Drender%20of%20the%20current%20row%20and%20re%2Dfetch%20the%20current%20schedule) regarding refreshing and re-fetching  only the updated recurring runs , rather than all of the recurring runs, I opted for this approach, but I am open to making changes, Please let me know your thoughts here

The big issue was that it was re fetching the whole api and not just recurring runs. Just fetching recurring runs is one call and not that big of a deal. Optimizing it further to instead fetching just the the changed run is still just one call so there is not any gain. Plus the added complexity of having have another state variable and needing to search though it and replace the singular item in the list. I think we should keep it simple and use the refresh from the table hook

**Comment by pnaik1** [comment]
Made the changes accordingly

**Review by DaoDaoNoCode — APPROVED** [review]
/unhold
/lgtm
This is a nice solution, I totally forgot we have refresh function for the table 😅

**Pull request merged**
