### PR TITLE
Make data connection bucket field mandatory

### LINKED ISSUE #1583: Make bucket field mandatory in new data connection for deploy model
### Feature description

A requirement in model serving is that every data connection needs to have a bucket name.
We need to make that field mandatory when creating a new data connection in the *Deploy model* modal.

### Mockups
(Is using the old field convention)

https://www.sketch.com/s/113593f8-5970-49d6-a352-709b07639127/a/P1oq14j#Comment

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1583 

## Description

Simply made the bucket field required.

Screenshot 2023-10-10 at 1 31 13 PM

## How Has This Been Tested?

1. Go to data science project details page
2. Create a model server
3. Try to deploy a model, select `New data connection`, make sure the `Bucket` field is required
4. Try to leave it as blank, make sure you cannot click deploy button

## Test Impact

Add some unit tests for `isAWSValid` function

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by lucferbux — CHANGES_REQUESTED** [review]
isRequired should only be mandatory in model serving

**Comment by lucferbux** [comment]
Maybe im wrong here but let me know @andrewballantyne @DaoDaoNoCode is that right?

**Comment by DaoDaoNoCode** [comment]
@lucferbux I confirmed with @andrewballantyne, you are right, it's only required here but not everywhere.

**Comment by vconzola** [comment]
@DaoDaoNoCode LGTM.

**Pull request merged**
