### PR TITLE
[RHOAIENG-4980] Fix RBAC on every tab for the action button

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Closes: [RHOAIENG-4980](https://issues.redhat.com/browse/RHOAIENG-4980)

## Description
Remove erroneous RBAC checks

## How Has This Been Tested?
Logged in as non-admin, verified I could create necessary items.

## Test Impact
None

## Request review criteria:
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)

### CODE REVIEW

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
Have you tested this with an edit user? The Permissions tab should not be visible to those users.

**Comment by jeff-phillips-18** [comment]
@andrewballantyne Rebase and added check before showing the permissions card.

**Comment by christianvogt** [comment]
@jeff-phillips-18 Logged in as a self-provisioner user who was granted `edit` access to a project and I still see the permissions tab as well as permissions card:
image

image

**Comment by christianvogt** [comment]
There's also this issue when trusty isn't disabled even though it should be. Maybe related to how tabs are being enabled and the permissions tab issue.
image

**Pull request merged**
