### PR TITLE
adding workflow to auto-add issues to project boards

### PR DESCRIPTION
**Pull request by dchourasia**
## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by andrewballantyne — COMMENTED** [review]
workflow looks good -- not sure why tests are failing. I've pinged @lucferbux to take a look when he gets a moment.

**Comment by lucferbux** [comment]
It's failing in the latest commit, @dchourasia can you squash and force push again? Not sure what's happening to prow, something weird in the Dockerfile build strategy

**Comment by dchourasia** [comment]
@lucferbux I have squashed all the latest commits from upstream main and pushed to my fork

**Comment by lucferbux** [comment]
Heh, it seemed a fluke, thanks @dchourasia that might have been the issue

**Review by lucferbux — APPROVED** [review]
/lgtm

**Pull request merged**
