### PR TITLE
Connection card update

### PR DESCRIPTION
**Pull request by ashley-o0o**
Closes: [RHOAIENG-13140](https://issues.redhat.com/browse/RHOAIENG-13140)

## Description
Updates the data connections card with new contents on both the home page and the data science projects page. The Connections card on the data science projects page now links to the connections tab.

## How Has This Been Tested?
Tested locally

## Test Impact
No tests added

## Screenshots
Screenshot 2024-10-07 at 3 37 15 PM

_----------------------_

Screenshot 2024-10-07 at 3 38 49 PM

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by christianvogt** [comment]
@ashley-o0o for now we still need to conditionally render the new connection type features behind the feature flag.

**Review by jeff-phillips-18 — APPROVED** [review]
Verified against current mocks
/lgtm

**Pull request merged**
