### PR TITLE
Enable Distributed Workloads feature flag by default in manifests

### PR DESCRIPTION
**Pull request by mturley**
## Description

Enables the Distributed Workloads feature by default for its GA in the upcoming release.

## How Has This Been Tested?

N/A

## Test Impact

N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by gitdallas — APPROVED** [review]

**Review by lucferbux — CHANGES_REQUESTED** [review]
Ok, there's a few things that we need to do for feature flags:

Add the same flag in `backend/src/types.ts` and `backend/src/utils/constants.ts`, since it's where odh will generate the flag.

Then add an entry in `docs/dashboard-config.md` explaining the feature, and in the defaults object (it's outdated, we should updated all of them).

And `odh-dashboard-config.yaml` is slightly deprecated, but it's fine to update that.

**Review by anishasthana — COMMENTED** [review]
The _intent_ of the PR lgtm -- we want to enable DW ui by default. I'll defer to @lucferbux on the implementation details.

**Comment by mturley** [comment]
@lucferbux thanks, updated and rebased

**Review by lucferbux — APPROVED** [review]
/lgtm

**Pull request merged**
