### PR TITLE
Restart the pods after updating configMap in workbench

### PR DESCRIPTION
**Pull request by ppadti**
Closes: [RHOAIENG-1210](https://issues.redhat.com/browse/RHOAIENG-1210)

## Description
This PR will add `notebooks.opendatahub.io/notebook-restart=true` to notebook CR to restart the pod after updating config map.

## How Has This Been Tested?
1. Create a workbench with adding the Environment variables (ConfigMap Environment variables type).
2.  after creation, update the config map. You can see that the pods will restart.

## Test Impact
NA, added an annotation. 

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by gitdallas — COMMENTED** [review]
code looks good to me, but i seem to be having trouble getting a workbench running. any ideas? i haven't done it before, and when i try, the status seems stuck at "starting", "Waiting for server request to start..."

**Comment by emilys314** [comment]
I was able to confirm that the workbench will restart when you update config maps environment variables

**Review by gitdallas — APPROVED** [review]

**Comment by jpuzz0** [comment]
I also checked this out and inspecting a particular pod's details belonging to the workbench I have, it appears the status of that pod updates before resuming "Running" again afterwards. I assumed this is how we'd verify the pods are restarted, but if not, I would like to know how this is meant to be done.

**Review by mturley — APPROVED** [review]
Verified this locally. I was able to see the pod restarting by finding it in the OCP console and seeing it get recreated there.

**Pull request merged**
