### PR TITLE
Update model registry status

### PR DESCRIPTION
**Pull request by ppadti**
Closes: [RHOAIENG-11278](https://issues.redhat.com/browse/RHOAIENG-11278)

## Description
This PR aims to update the status of the model registry by adding refresh interval.

## How Has This Been Tested?
1. create a model registry.
2. check that the status of the model registry will update when it is available.

## Test Impact
NA

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by ppadti** [comment]
@mturley I am not sure should we use `FAST_POLL_INTERVAL` here until the status gets updated like we have for workbenches here: https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx#L25

**Review by gitdallas — APPROVED** [review]
lgtm, but i'm unsure of the answer to your question about using the faster interval. possibly something to discuss with design or pm

**Comment by mturley** [comment]
@ppadti let's leave it as the 30-second `POLL_INTERVAL` for now. There's a separate problem we need to address post-MVP where the registry is showing as Unavailable right after it's created ([see thread here](https://redhat-internal.slack.com/archives/C07C0447EAV/p1724847598941919), I don't think we have an issue yet) which would complicate the logic of determining whether to use the faster poll interval here. If we decide we want to add that behavior after that is fixed we can revisit it I think.

**Review by mturley — APPROVED** [review]
LGTM, thanks @ppadti

**Pull request merged**
