### PR TITLE
Misc Improvements for DSG

### PR DESCRIPTION
**Pull request by andrewballantyne**
Resolves: #768 

## Description

Some misc feedback we got from QE, UX & PM.

- Minor text changes were also made where applicable to help with wording consistency
- Updated the Spawner Page in DSG not to use Ephemeral and assume a like-named resource name for the PVC that is created as part of the flow
- Added note to showcase that PVCs in Create Workbench flow mount to the root
- Support folder mount names in expanded Workbenches
- Added a pointer finger cursor for the "starting..." text that Workbenches show; live status is hidden behind here

Images:

image

image

### CODE REVIEW

**Review by DaoDaoNoCode — APPROVED** [review]
lgtm

**Comment by andrewballantyne** [comment]
I've expanded this to cover some misc items to make it clearer and more useful to the user to use. Feedback was gathered from QE, UX and PM.

I'll talk with Berto tomorrow to see what the cost to QE testing is and hopefully work to get it in for the next release.

**Comment by andrewballantyne** [comment]
Confirmed with Berto, going ahead with trying to get this into the next release.

**Review by DaoDaoNoCode — APPROVED** [review]
lgtm

**Pull request merged**
