### PR TITLE
Add OVMS OOTB with GPU support

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Closes: #1257 

## How Has This Been Tested?

1. Deploy the manifest files
2. Check that you can see both Custom Serving Runtimes as pre-installed

## Test Impact

Test will be done in the follow up testing section for Custom Serving Runtime

Screenshot 2023-05-19 at 16 01 27
Screenshot 2023-05-19 at 16 01 17

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by lucferbux** [comment]
@vconzola I've attached a screenshot just to validate if this is what you were expecting, maybe we can review the name of the GPU one

**Comment by lucferbux** [comment]
@Xaenalt If we can validate the spec it would be super helpful, I'm still confused about the different images in ovms.

**Comment by andrewballantyne** [comment]
> @vconzola I've attached a screenshot just to validate if this is what you were expecting, maybe we can review the name of the GPU one

I think we wanted to go with `(GPU Required)` as it can't work on a non-GPU node.

**Comment by vconzola** [comment]
@lucferbux Actually, seeing how this looks to the end user, maybe "Supports GPUs" makes more sense than "GPU required". What do you think?

**Comment by lucferbux** [comment]
> I didn't realize that both runtimes would have the exact same name. Yuck! But it is what it is. Instead of parenthetical text after the name, can we put "GPU required" in a label, just like "Pre-installed". I think that will draw more attention.

mmmm, the hole point of getting this to the display name is that is displayed in the selection of the runtime (I'm gonna attach new screenshots). We can add a label too, but what should we do in the modal selection?

**Comment by lucferbux** [comment]
@vconzola 

Screenshot 2023-05-19 at 16 01 27
Screenshot 2023-05-19 at 16 01 17

**Comment by Xaenalt** [comment]
Looks good to me, we validated the correct image tag to use as well

**Review by andrewballantyne — APPROVED** [review]
/hold

This looks good by all parties -- only holding until I get confirmation from Lucas.

**Comment by lucferbux** [comment]
> /hold
> 
> This looks good by all parties -- only holding until I get confirmation from Lucas.

It should be fine by now, based on conversations we had this should be the image, already tested so it's working as intended.

**Pull request merged**
