### PR TITLE
Update layout in the pipelines and runs node side panel

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
JIRA: https://issues.redhat.com/browse/RHOAIENG-7944

## Description

Update the layout in the side panel to make it align with the design. Mainly made the following changes:
1. Use Flex layout instead of Stack to better set the space between sections
2. Based on the mockup, we wrap the text of the long parameter names instead of truncating them. Here I removed the `Truncate` component and use `DescriptionList` for the layout, and set a width for the terms.

Screenshot 2024-08-26 at 3 45 21 PM

Screenshot 2024-08-26 at 3 45 51 PM

## How Has This Been Tested?

1. Import some pipelines
2. Check the pipeline node on pipeline version details page, make sure the definitions text are correctly wrapped
3. Create some runs
4. Check the executions node and make sure the space between sections are similar to the mockups

## Test Impact

N/A, layout changes only, we need UX approvals.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@yannnz Hello, could you check the ticket and the screenshot above to make sure the current change matches the design?

**Comment by yannnz** [comment]
> @yannnz Hello, could you check the ticket and the screenshot above to make sure the current change matches the design?
Hi @DaoDaoNoCode , is this task focusing on increasing the spacing between sections while making them consistent in the drawer for a more readable layout?  If so, the screenshots look good to me.

**Comment by DaoDaoNoCode** [comment]
@yannnz Yes, and it also change the wrapping of the param names (the bold font in the screenshot above), it was truncated before and now we wrap it as is shown in the mockup.

**Review by Gkrumbach07 — COMMENTED** [review]
screenshots and code looks good. This also looks to cover all our drawer views

/lgtm

**Review by jpuzz0 — APPROVED** [review]

**Pull request merged**
