### PR TITLE
add ovms-kserve template

### PR DESCRIPTION
**Pull request by rpancham**
Closes: [RHOAIENG-2072](https://issues.redhat.com/browse/RHOAIENG-2072)

## Description

 Create and add OVMS KServe template.

## How Has This Been Tested?

It is a Manifest so no need of Testing.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by lucferbux — COMMENTED** [review]
/lgtm

Ok, code looks great, I'm gonna approve it but I might open a follow up issue (UI related) regarding this.
Screenshot 2024-01-26 at 16 56 48

@vconzola I want your opinion on this, turns out they are both ovms but they have different specs, one is supported for kserve and the other one for modelmesh, we might wanna end up implementing something to make sure one same serving runtime can have different specs for either modelmesh or kserve, what do you think?

**Comment by vconzola** [comment]
@lucferbux I thought we already addressed this with the "Serving platforms supported" on each runtime? The screenshot seems to show the scenario you're describing - one runtime (OVMS) with two different specs (muti-model and single model). What am I missing?

**Comment by lucferbux** [comment]
> @lucferbux I thought we already addressed this with the "Serving platforms supported" on each runtime? The screenshot seems to show the scenario you're describing - one runtime (OVMS) with two different specs (muti-model and single model). What am I missing?

No, that's it, i was wondering if we would like to have in the feature something to gather those two in the same entry, but don't worry about that

**Pull request merged**
