### PR TITLE
Fix page title sentence casing

### PR DESCRIPTION
**Pull request by dgutride**
## Description

Changed three page titles to match the navigation item casing.  Top level items should be Title Case, all nested items should be Sentence case.  

Cluster settings (was Cluster Settings), User management (instead of User and group settings) and Data Science Projects (instead of Data science projects since it's a top level item) were all changed.

## How Has This Been Tested?

Ran the site locally, loaded all impacted pages and ensured that the page title now matches the navigation item on the left hand side.

## Test Impact

Ran storybook and other tests before putting up PR - none needed adjustment.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

Closes: #1907

### CODE REVIEW

**Comment by lucferbux** [comment]
🎉🎉🎉🎉
@dgutride We might want to tag @kywalker-rh and @kaedward, in case they want to be aware and maybe we can update future mockups with this labels.
Tested locally and works great, I'll wait to UX first before lgtm it

**Comment by andrewballantyne** [comment]
@dgutride the template asks for you to tag a UX person if there are UI changes... but in this case there is already a UX decision made... but we should always reping them to make sure we delivered on their ask. Lucas tagged Katie.

**Comment by andrewballantyne** [comment]
Also @dgutride ... From a scan of the code, you're missing [Model Serving](https://github.com/opendatahub-io/odh-dashboard/blob/f940019c835edb72cc199a58c7f81d3d6d737c3e/frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx#L15). I'm spinning up a Cluster Bot cluster to make sure I can get a state in there somehow to see the page. Looks like Model Serving is having some issues on our shared cluster.

**Comment by andrewballantyne** [comment]
So this looks good... my only question is for @kaedward... what about breadcrumbs? It's not often we have them, but:

image
image

@dgutride we squash commits too -- so an FYI we will need to get you down to one commit before we merge.

**Comment by kaedward** [comment]
@andrewballantyne Breadcrumbs should match the casing of the navigation item and the project/item's casing - so "Data Science Projects > Andrew's test" (If that's how the project name is capitalized)

**Comment by andrewballantyne** [comment]
@dgutride there is another fix you need to do -- there are a few breadcrumb values that need to be updated as well to fit the page naming. There are two "Data science projects" items for breadcrumbs that need to be updated and I think actually there is one for Data Science Pipelines that I just called "Projects" which needs to be updated too.

If you search for these things you should be able to find all 3 easily:
- `>Data science projects<` (should have 2 results)
- `>Projects<` (should have 1 result)

**Comment by dgutride** [comment]
Fixed Data Science Project breadcrumbs, too - here's a few screenshots:
Screenshot 2023-11-07 at 1 41 22 PM

Screenshot 2023-11-07 at 1 41 59 PM

**Comment by dgutride** [comment]
Screenshot 2023-11-07 at 1 44 33 PM

**Review by andrewballantyne — APPROVED** [review]
Looks good... We have some bugs in the way Pipelines references items inside a project vs the global page, but that's definitely separate of this initiative. I'll look to log something soon.

**Pull request merged**
