### PR TITLE
Enable pipeline experiments in dashboard config

### PR DESCRIPTION
**Pull request by Gkrumbach07**
closes: https://issues.redhat.com/browse/RHOAIENG-3826

## Description

- set experiments feature flag on instead
- moved all navigation to go to `/pipelines` and not `/pipelineRuns`
- created the runs based on version details page

## How Has This Been Tested?

- test all routes and make sure they dont go to `/pipelineRuns`
- test that version details page shows only runs and jobs from its version and the table does not have a version col

## Test Impact

will need to updated routes tests

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
I can still access the global pipeline runs page via URL, should we also remove that and make it a 404 since we don't use that page anymore?

Screenshot 2024-06-11 at 12 48 54 PM

**Comment by Gkrumbach07** [comment]
Andrew said to keep it around. as long as we cant get to it from supported flows @DaoDaoNoCode

**Comment by Gkrumbach07** [comment]
@DaoDaoNoCode I updated the PR

**Comment by DaoDaoNoCode** [comment]
@Gkrumbach07 Can you rebase the PR?

**Review by DaoDaoNoCode — COMMENTED** [review]
The link [here](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsReferenceSection.tsx#L44) on execution details page needs to be updated, otherwise it will navigate to old global pipeline run details page.

**Review by DaoDaoNoCode — APPROVED** [review]
Tested all the routes I could think of, it works well.
/lgtm

**Comment by Gkrumbach07** [comment]
@DaoDaoNoCode I ended up finding a clean solution for it

**Review by dpanshug — APPROVED** [review]
/lgtm

**Comment by Gkrumbach07** [comment]
merging this

/approve

**Pull request merged**
