### PR TITLE
improve cypress commands to better support running a single test spec

### PR DESCRIPTION
**Pull request by christianvogt**
https://issues.redhat.com/browse/RHOAIENG-2971

## Description

Add support to the existing cypress scripts in the frontend package.json to execute a single cypress test spec:
`npm run test:cypress-ci -- --spec "**/mytest.cy.ts`
`npm run cypress:run:mock -- --spec "**/mytest.cy.ts`

## How Has This Been Tested?

Run a test with a single command:
`npm run test:cypress-ci -- --spec "**/explore.cy.ts`

Run a server in one terminal:
`npm run cypress:server:build && npm run cypress:server`
Run cypress tests in another:
`npm run cypress:run:mock -- --spec "**/explore.cy.ts`

## Test Impact

none

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by christianvogt** [comment]
rebased PR

**Review by andrewballantyne — COMMENTED** [review]
This is exactly what I was asking for -- question for ease of use -- I imagine most IDEs can "copy path from root" when looking at a cypress test file... I wonder if we should add the ability to CI Cypress invoke from the root -- because obviously `frontend/src/...` is what you will get by "copy path from root" on a cypress test file

**Review by andrewballantyne — APPROVED** [review]
Looks good -- we may be able to improve this later with direct file paths from the root -- but globs can solve this for now. 

I imagine it will be `**/{fileNameHere}` sorta detalio -- but it's up to the dev who makes the command to verify that does what they want.

**Pull request merged**
