### PR TITLE
Task/rhoaieng 12667  tech debt cleanup duplicate code in pipelines co

### PR DESCRIPTION
**Pull request by Gkrumbach07**
https://issues.redhat.com/browse/RHOAIENG-12667

## Description

Fixes duplicate code in pipelines based on the output of
```bash
npx jscpd . --ignore "**/*.spec.*,**/__tests__/**" -r html --ignore-pattern "import.*from\s*'.*'" -l 20 --pattern "**/pipelines/**"
```

I choose 20 because anything smaller was not worth creating shared components. There are some still in the 20 line range but those could not be created into shared components or it was unnatural to make them into a shared component. At 30 lines, all duplication was removed.

## How Has This Been Tested?

Test each area of duplication. they are separated by commit.
1. Import pipeline and import pipeline version modal
2. pipeline run table toolbar (search dropdown)
   - can be seen in compare runs, compare runs manage runs, and run list page
3. pipeline active runs table empty state and compare runs manage runs empty state
4. larger breadcrumbs in pipelines
5. experiment active and archived loading error

## Test Impact

make sure tests still pass

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@Gkrumbach07 Can you fix the cypress test?

**Comment by pnaik1** [comment]
@Gkrumbach07 , everything looks good except the breadcrumb separation of pipeline and pipeline version

Screenshot 2024-10-15 at 6 50 22 PM

**Review by jpuzz0 — APPROVED** [review]
Tested locally. The areas mentioned work as expected. Code changes look good as well.

**Comment by jpuzz0** [comment]
> @Gkrumbach07 , everything looks good except the breadcrumb separation of pipeline and pipeline version
> 
> Screenshot 2024-10-15 at 6 50 22 PM

@Gkrumbach07 at first I wasn't seeing this but now I am. To be clear, this occurs when creating a run via the row action of the pipelines table, not from the runs list. There are different experiences here that lead to a different set of breadcrumbs.

**Review by jpuzz0 — APPROVED** [review]

**Pull request merged**
