### PR TITLE
Make custom image location regex match return correct full URL

### LINKED ISSUE #1641: [Bug]: Cannot use SHA256 as the image tag
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

v2.14.0

### Current Behavior

When you go to the notebook image settings and try to import a notebook image, if you use SHA256 code as the notebook tag, you will not be able to get the correct tag because the tag will be removed and it will find the `latest` tag instead.

### Expected Behavior

Users can import SHA256-encoded tag.

### Steps To Reproduce

1. Go to `Notebook image settings`
2. Try to import an image using SHA256-encoded tag like `quay.io/opendatahub/workbench-images@sha256:b6532b34c9bf0710ecbd76407c8909742914bdacd17add3e04ab49e7c81a2800`
3. You will find the image will throw some errors, and when you expand the row, you will find the image location doesn't contain the tag

### Workaround (if any)

No

### What browsers are you seeing the problem on?

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #1641 

## Description

It's because the image regex is returning the full match result as the URL but not the full URL, so the tag is omitted.

## How Has This Been Tested?

Follow the same way in the issue description:
1. Go to Notebook image settings
2. Try to import an image using SHA256-encoded tag like `quay.io/opendatahub/workbench-images@sha256:b6532b34c9bf0710ecbd76407c8909742914bdacd17add3e04ab49e7c81a2800`
3. Make sure the image can be successfully imported and the image location is shown correctly

## Test Impact

N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [x] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by alexcreasy** [comment]
@DaoDaoNoCode have you built this and tested it on a cluster?

**Comment by DaoDaoNoCode** [comment]
@alexcreasy yes, I did that the last moment before my demo started :P

**Review by alexcreasy — APPROVED** [review]
Built an image and tested on my cluster, works great!

**Comment by alexcreasy** [comment]
> @alexcreasy yes, I did that the last moment before my demo started :P

Then pls tick the box from the template :)

**Comment by DaoDaoNoCode** [comment]
@alexcreasy Ah because it's not going to `main`, it's going to `incubation`

**Comment by alexcreasy** [comment]
> @alexcreasy Ah because it's not going to `main`, it's going to `incubation`

@DaoDaoNoCode yeah, good point, I'll create a new template for going to incubation tomorrow morning my time!

**Pull request merged**
