### PR TITLE
Update microcopy for Bias & Performance metrics

### PR DESCRIPTION
**Pull request by alexcreasy**
Closes:
  * [RHOAIENG-252](https://issues.redhat.com//browse/RHOAIENG-252)
  * [RHOAIENG-1847](https://issues.redhat.com//browse/RHOAIENG-1847)
## Description

Implements suggestions from microcopy review described here: https://docs.google.com/document/d/1Jgzo9ZoNYeYmyAtTV1v-JzDWHnotM5aVwnL1NRZPjOA/edit#heading=h.bz4zmg8x9xcy

Updated screens:
localhost_4010_projects_model-namespace

localhost_4010_projects_model-namespace

localhost_4010_projects_model-namespace (1)

localhost_4010_projects_vince-test

localhost_4010_projects_vince-test

localhost_4010_projects_vince-test

localhost_4010_projects_vince-test

localhost_4010_projects_vince-test

localhost_4010_projects_vince-test (1)

## How Has This Been Tested?

* Verify string changes described in linked doc have been made.

## Test Impact

N/A changes strings only
## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [x] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by alexcreasy** [comment]
Fixed failing tests and lint errors, rebased against main.

**Comment by alexcreasy** [comment]
CC: @kaedward just FYI this implements the changes from your review.

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm

only things missing need to be done in a future issue
- tooltip for disabled https://docs.google.com/document/d/1Jgzo9ZoNYeYmyAtTV1v-JzDWHnotM5aVwnL1NRZPjOA/edit?disco=AAABEewQSwQ
- change delete modal logic https://docs.google.com/document/d/1Jgzo9ZoNYeYmyAtTV1v-JzDWHnotM5aVwnL1NRZPjOA/edit?disco=AAABEewQSxM

**Pull request merged**
