### PR TITLE
Truncate long display name in serving runtimes

### PR DESCRIPTION
**Pull request by ppadti**
Closes: #1394

## Description
This PR will truncate the long display name in "serving runtimes" and table will not expand as large as name.

Screenshot from 2023-08-30 13-41-29

## How Has This Been Tested?
1. Go to serving runtimes page
2. Create a new serving runtime with a long display name
3. After creation of new serving runtime, the long display name will be truncated and table will not expand as before.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by christianvogt** [comment]
@ppadti Can you make it such that the `?` icon does not wrap to the next line.

**Comment by christianvogt** [comment]
The latest commit does keep the icon on the same line on desktop view however the icon is overflowing the layout:
image

But on mobile, the icon once again wraps:
image

Thinking about this some more, perhaps using `Truncate` isn't the best approach. We have lots of real estate to support wrapping. Perhaps apply `word-break: break-word` css style to the container instead. Use the PF utility class `pf-u-text-break-word`. This would still solve the issue with the table layout stretching beyond the window width.

cc @lucferbux

**Comment by christianvogt** [comment]
Similar issue raised here: https://github.com/opendatahub-io/odh-dashboard/issues/1182#issuecomment-1702896458

**Comment by ppadti** [comment]
UI will look like this after adding PF utility class

Screenshot from 2023-09-05 19-13-53

**Comment by vconzola** [comment]
@ppadti Why are you merging visual changes like this without informing UX? cc: @andrewballantyne

**Comment by christianvogt** [comment]
@vconzola I guess I incorrectly assumed that UX only needed to be pinged on changes that have a visual impact that would change what a mock had previously suggested. In future I'll ensure that PRs will tag UX before they are approved.

I approved this PR because it only fixes the broken layout in extreme circumstances. The content and table rendering are unaffected - text previously wrapped to multiple lines. The applied style only tells the browser how to break up long continuous words that would otherwise result in a broken layout. Under normal circumstances, the layout is exactly the same as before.

Note that it seems the screenshots in the description were not updated to the latest which were posted above.

**Comment by vconzola** [comment]
@christianvogt The reason I brought it up is that it's a best practice for truncated text fields to display a tooltip (on hover) that shows the full text. I couldn't tell from the PR if that was implemented?

**Comment by christianvogt** [comment]
@vconzola In this case the text is not being truncated (the screenshot in the description wasn't updated but those in the comments show the latest) and the original solution to make use of PF `Truncate` component was not used but instead a style applied that would allow singular long words that do not contain breaks to wrap. Note, this was already the default behavior implemented by PF on mobile. For whatever reason PF only applies this for mobile by default to their table layouts but not to the desktop layout. Also, the current behavior of wrapping text is present in every table in ODH dashboards today - only singular long words without breaks failed to wrap while those containing spaces or other word breaking characters do wrap.

eg. projects list on mobile showing wrapped long words by default
image

**Comment by vconzola** [comment]
Thanks @christianvogt . Not the way I would go wrt to wrapping, but I understand if that's what ODH is doing elsewhere.

**Pull request merged**
