### PR TITLE
Unit Test Case for useInferenceServices

### PR DESCRIPTION
**Pull request by uidoyen**
Closes: [RHOAIENG-1852](https://issues.redhat.com/browse/RHOAIENG-1852)

## Description
Unit test case for: frontend/src/pages/modelServing/useInferenceServices.ts

## How Has This Been Tested?
`npm run test`

## Test Impact
Screenshot 2024-01-20 at 1 26 01 AM

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by christianvogt** [comment]
@uidoyen please add another test for the missing code coverage. You can assert that `k8sListResourceMock` has not been called when the `NotReadyError` use case is encountered.

**Comment by uidoyen** [comment]
> @uidoyen please add another test for the missing code coverage. You can assert that `k8sListResourceMock` has not been called when the `NotReadyError` use case is encountered.

@christianvogt Updated the test case based on your comment as well as the latest hook update.

**Comment by christianvogt** [comment]
@uidoyen you don't have a test case for when `namespace` is not provided as a param to the hook.

**Comment by uidoyen** [comment]
@christianvogt added test case when `namespace` isn't provided. Can you please check it again?

**Pull request merged**
