### PR TITLE
websocket for notebooks scheduling

### PR DESCRIPTION
**Pull request by Gkrumbach07**
https://issues.redhat.com/browse/RHOAIENG-6705

## Description

1. commit 1: uses websockets for events with notebook startup
2. commit 2: uses websockets for notebooks (THIS IS MAY NEED TO BE REMOVED BC IT TOUCHES A LOT)

## How Has This Been Tested?

open two dashboard tabs and turn on and off notebook. events should be using websockets as seen in network tab of browser debug

## Test Impact

adjust tests to expect websockets

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
Can we remove this file https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/projects/notebook/useWatchNotebookEvents.ts?? since we are replacing it with websocket hook

**Comment by Gkrumbach07** [comment]
ok @pnaik1 I removed that file. in addition i remove the same hook for fetch events for the jupyter spawner and adjusted some types to account for it

I will keep this getNotebookEvents and its related backend route just in case its needed later on

**Comment by pnaik1** [comment]
tested in locally with two tab running simultaneously, stopping and starting notebook in workbench page uses websocket
and also the notebook controller uses the websocket event log
/lgtm

**Review by DaoDaoNoCode — APPROVED** [review]
/lgtm

**Pull request merged**
