### PR TITLE
Pipeline (run) filter, sorting and paging through server side APIs

### PR DESCRIPTION
**Pull request by christianvogt**
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/1223

## Description

cc @yannnz 

Features:
- Updates pipelines, pipeline runs (triggered and scheduled) to perform filtering, sorting, and paging through the kf api
- Paging supports 10, 20, 30
- Changing sort order, sort field, or a change to filters will bring the user back to page 1
- Selection is dropped when the page changes (or anything that affects the page to change). Returning to a previous page which contained selections will result in no selection.
- User must always wait for the current page to load before proceeding to the next page
- User can go back to previous pages as quickly as they want because the page tokens have been cached
- Loading skeletons are always shown as the user navigates pages
- Table row heights are cached such that the table maintains a consistent size as the user navigates pages
- While switching pages, the number of shows shown loading is always equal to the number of rows that will be presented because we know before hand how many items will appear on that page. In rare circumstances could the number of items change between loading in which case the table automatically adjusts to accommodate the new data.
- Data per page is refreshed continuously as before every 30 seconds

Filtering and sorting limitations is limited:
- pipelines: filtering and sorting limited to name and created on
- pipeline runs - triggered: filtering and sorting limited to name, started, status and filtering on experiment
- pipeline runs - scheduled: filtering and sorting limited to name

image
image
image
image
image
image
image

Loading state. Each row keeps the size of the row on the previous page to prevent page resizing while changing page. Since pipeline runs contain a cell with a `name, description, label` they are extra tall.
image

image
image

Limited pipeline table:
image
Sorted by name:
image
image

Minor updates to to align with mocks:
image

NOT IMPLEMENTED: Filtering pipeline runs on by related pipeline name. 
image

## Test Impact

Added unit tests for hooks related to 

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by andrewballantyne** [comment]
> NOT IMPLEMENTED: Filtering pipeline runs on pipeline and experiement. Filtering of pipeline or experiement can only be done by ID as a separate filter.
> image

Let us skip this implementation for this PR. 

* Pipelines => Don't filter well
* Experiments => Are not really supported at a top-level yet (see `f/pipeline-experiments` branch for that)

**Comment by christianvogt** [comment]
@andrewballantyne filter now supports experiments but no pipeline

**Comment by christianvogt** [comment]
@yannnz could you please have a look at the screens

**Comment by yannnz** [comment]
For filter, if I remember it correctly, for Triggered runs, we have Name, Experiment, Pipeline (should be pipeline versions once we implement the version), Started, Status. For Scheduled runs, we have Name, Experiment and Pipeline (should also be pipeline versions).

For pipelines, I didn't do the design without the pipeline versions. So I am not sure what is the limited pipeline table for.

**Comment by christianvogt** [comment]
@yannnz I spoke with @andrewballantyne about the filtering of pipeline references for runs and he suggested not implementing because of pipeline versions not supporting it.

**Comment by andrewballantyne** [comment]
> @yannnz I spoke with @andrewballantyne about the filtering of pipeline references for runs and he suggested not implementing because of pipeline versions not supporting it.

We can always swing back... but in the current model, it's not worth implementing. Maybe it can come with Pipeline Versions

**Comment by andrewballantyne** [comment]
/hold

Let me see if we can work this out a little better for releasing. If we merge it into this feature branch, it's tied to the fate of pod logs... they are unrelated. I'm working with Dana to see how we can support stuff better.

I'll also review this now too.

**Review by DaoDaoNoCode — COMMENTED** [review]
I tested the functionalities mentioned above and they all work as expected. Only one thing I noticed that's not related to this PR. But it could be obvious when we delete many runs at the same time, the `PendingIcon` looks weird here. I guess we need to use the `Icon` component to wrap it.

Screenshot 2023-10-13 at 2 57 04 PM

**Comment by christianvogt** [comment]
@DaoDaoNoCode Your screenshot looks odd. It looks like where is an issue with using PF `ListItem` with an `icon` because it assigns `pf-c-list__item` which makes the list item a flex layout causing all children to have incorrect spacing and heights.

This isn't something I changed in my PR but should be addressed separately on the feature branch.

**Comment by andrewballantyne** [comment]
@DaoDaoNoCode @christianvogt I imagine the delete modal can be fixed up in https://github.com/opendatahub-io/odh-dashboard/issues/1791. I'll add it to that ticket's objective. Let us not do it part of this one.

**Comment by christianvogt** [comment]
It was decided to retarget this PR to `main`.

**Review by manaswinidas — COMMENTED** [review]
I saw something weird, why is the design getting "compressed?" after triggering a Delete? I have an example. It only happens briefly though(just after you trigger a Delete and before the Delete modal closes). Not sure if this is related.

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/8b17c63f-208b-4578-bef4-c588f1a2d23a

**Comment by DaoDaoNoCode** [comment]
@christianvogt Please check this, looks like the list item layout is broken when there are 3 elements on a row.

Screenshot 2023-11-17 at 12 26 38 PM

**Comment by christianvogt** [comment]
The hold on this PR was removed but this needs to be updated with the latest on the branch as it hasn't been updated in quite some time. I'll check out the issues that were recently identified.

I'll confirm if this PR should retarget main or stay on this branch.

**Comment by christianvogt** [comment]
@DaoDaoNoCode I fixed the error with the invalid date input. The UI now looks like this:
image

I create a new component to help with the error handling of date picker inside a toolbar. See `DashboardDatePicker`

**Comment by christianvogt** [comment]
@manaswinidas I fixed the layout issue with the delete modal. This occurred because PF changes the list item layout whenever an icon is present. The icon appears during the deletion. I simply added a nested `<div>` to control the layout of the children without being affected by change in layout when the icon is added.

**Review by DaoDaoNoCode — APPROVED** [review]
/lgtm
nice work

**Pull request merged**
