### PR TITLE
Add accelerator support to Custom Serving Runtimes

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Closes https://issues.redhat.com/browse/RHODS-12899

## How Has This Been Tested?

Just added this Custom Serving Runtime:

```yaml
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ovms-accelerator
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/ootb: 'true'
  annotations:
    tags: 'ovms,servingruntime'
    description: 'OpenVino Model Serving Definition Accelerator'
    opendatahub.io/modelServingSupport: '["multi"]'
objects:
  - apiVersion: serving.kserve.io/v1alpha1
    kind: ServingRuntime
    metadata:
      name: ovms
      annotations:
        openshift.io/display-name: 'OpenVINO Model Server Accelerator'
        opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
      labels:
        opendatahub.io/dashboard: 'true'
    spec:
      builtInAdapter:
        env:
          - name: OVMS_FORCE_TARGET_DEVICE
            value: AUTO
        memBufferBytes: 134217728
        modelLoadingTimeoutMillis: 90000
        runtimeManagementPort: 8888
        serverType: ovms
      containers:
        - args:
            - '--port=8001'
            - '--rest_port=8888'
            - '--config_path=/models/model_config_list.json'
            - '--file_system_poll_wait_seconds=0'
            - '--grpc_bind_address=127.0.0.1'
            - '--rest_bind_address=127.0.0.1'
          image: ovms-1
          name: ovms
          resources:
            limits:
              cpu: '0'
              memory: 0Gi
            requests:
              cpu: '0'
              memory: 0Gi
      grpcDataEndpoint: 'port:8001'
      grpcEndpoint: 'port:8085'
      multiModel: true
      protocolVersions:
        - grpc-v1
      replicas: 1
      supportedModelFormats:
        - autoSelect: true
          name: openvino_ir
          version: opset1
        - autoSelect: true
          name: onnx
          version: '1'
        - autoSelect: true
          name: tensorflow
          version: "2" 
parameters: []
```

And tried to deploy a modelmesh server.
Screenshot 2024-01-04 at 15 58 23

## Test Impact

No needed, just updated some config files

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by lucferbux** [comment]
@dtrifiro @Jooho @heyselbi Please confirm if we should add the annotations in caikit too.

thanks in advance.

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm annotation is formatted right

**Comment by lucferbux** [comment]
> @dtrifiro @Jooho @heyselbi Please confirm if we should add the annotations in caikit too.
> 
> thanks in advance.

Can we have confirmation @Jooho @heyselbi @dtrifiro @Xaenalt ?

**Comment by Xaenalt** [comment]
Yes, caikit+TGIS supports Nvidia cards, and should be annotated as such

Also, one nit, with:
```
          - name: OVMS_FORCE_TARGET_DEVICE
            value: AUTO
```
OVMS actually supports both Nvidia and non-Nvidia scenarios with the AUTO device, so shouldn't be necessary to have two entries anymore

**Comment by lucferbux** [comment]
> OVMS_FORCE_TARGET_DEVICE

Great, thanks a lot. What do you mean about two entries? I don't understand that part.

**Pull request merged**
