### PR TITLE
Show all the nodes in pipeline details topology

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
JIRA: https://issues.redhat.com/browse/RHOAIENG-5349

## Description

Refine the logic to recursively render all the tasks on the pipeline details page before we have a solution for the stacked topology node.

Screenshot 2024-04-12 at 1 17 20 PM

## How Has This Been Tested?

1. Import the flip coin pipeline (the file is in the JIRA ticket)
2. View the pipeline version details
3. Check whether all the nodes/tasks are rendered on the topology graph and you can view their details

## Test Impact

N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
reviewed with dev, we are able to render groups flat now.

**Review by Gkrumbach07 — APPROVED** [review]

**Comment by lucferbux** [comment]
/override ci/prox/images ci/prow/odh-dashboard-pr-image-mirror

**Comment by lucferbux** [comment]
/override ci/prow/images ci/prow/odh-dashboard-pr-image-mirror

**Pull request merged**
