### PR TITLE
NO-JIRA: chore(quality): add `data-testid` for the Launch standalone notebook server button

### PR DESCRIPTION
**Pull request by jiridanek**
## Description

* https://github.com/red-hat-data-services/ods-ci/pull/1880#issuecomment-2387950341

## How Has This Been Tested?

PR checks

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges: quay.io/opendatahub/odh-dashboard:pr-3294
- [x] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by jiridanek** [comment]
/unhold

the data-testid is present

## before

image

## now

Screenshot 2024-10-04 at 8 50 07 AM

**Comment by jiridanek** [comment]
/cc manosnoam
that's the right command , https://prow.k8s.io/command-help#cc

**Review by manosnoam — APPROVED** [review]
lgtm

**Pull request merged**
