### PR TITLE
Set enableServiceLinks to false

### LINKED ISSUE #306: [KFNBC]: os.environ in a nb server exposes IP addresses of all running nbs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I do 
```
import os
print(os.environ)
```
in a notebook server, I will get back a list of environment variables, which include IPs for all running notebooks (along with ports for connection, which are the default 443/80, but could be more sensitive if we had custom port mapping).

### Expected Behavior

I should not be getting the IPs of everyone else's notebook servers

### Steps To Reproduce

Spawn a notebook
in a code cell, write
```
import os
print(os.environ)
```

### Workaround (if any)

_No response_

### OpenShift Version

_No response_

### Openshift Version

_No response_

### What browsers are you seeing the problem on?

_No response_

### Open Data Hub Version

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Closes #306

### CODE REVIEW

**Comment by samuelvl** [comment]
@VaishnaviHire Could you review this change? It should fix https://github.com/opendatahub-io/odh-dashboard/issues/306

**Comment by VaishnaviHire** [comment]
/lgtm

Worked well on local build of the dashboard

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

Worked well on local build of the dashboard

**Review by andrewballantyne — APPROVED** [review]
Significant reduction in the env vars, lgtm.

**Review by samuelvl — APPROVED** [review]
/lgtm

**Pull request merged**
