### PR TITLE
relicense project to Apache 2.0

### PR DESCRIPTION
**Pull request by gregsheremeta**
relicense project to Apache 2.0 per the recent Open Data Hub accepted ADR, https://github.com/opendatahub-io/architecture-decision-records/blob/main/ODH-ADR-0003-use-apache-2-0-licence.md

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@gregsheremeta what is the process here? How do we go about accepting a license change?

**Comment by gregsheremeta** [comment]
> what is the process here? How do we go about accepting a license change?

No to-do here other than merge he PR. We've already agreed at the Open Data Hub community level to relicense to Apache 2.0. [ODH-ADR-003 (Accepted)](https://github.com/opendatahub-io/architecture-decision-records/blob/main/ODH-ADR-0003-use-apache-2-0-licence.md) that captures that decision.

**Review by andrewballantyne — APPROVED** [review]

**Pull request merged**
