### PR TITLE
minimize jest output in CI

### PR DESCRIPTION
**Pull request by christianvogt**
https://issues.redhat.com/browse/RHOAIENG-7215

## Description

Uses jest `--silent` option to minimize the noise produced by jest in the logs.
Also updates the code coverage reporters to exclude `text` for the coverage CI commands.

Can still run test with `test:jest` and add any command line options when using jest locally.

Inspect PR logs for length of output.

## How Has This Been Tested?

`npm run test:unit`
`npm run test:jest:coverage`

## Test Impact

N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
This mutes console message, but running `npm run test:jest:coverage` doesn't displays the coverage report in the terminal as it was doing  before, is it expected behaviour?

**Comment by christianvogt** [comment]
@pnaik1 yes it is expected for the CI command to no longer output the coverage report in the terminal. The coverage report is still available in a json summary and HTML report on the `frontend/jest-coverage` directory.

Devs can also run `npm run test:jest -- --coverage` to get the full coverage as before. Or they can run `npm run test:jest:coverage -- --coverageReporters=text` to add the text coverage report output to the terminal.

The table is very large not that useful to look at. The summary report is more useful. Furthermore we are interested in the merged coverage of both unit and cypress tests.

**Pull request merged**
