### PR TITLE
feat: add GH action to scan files in repo on PR basis

### PR DESCRIPTION
**Pull request by zdtsw**
## Description
Add new GitHub Action to do vulnerability scanning on static file in the repo on any PR
Result stored as artifacts in json format can be downloaded from Action runs' Artifacts zip file.
Only record if vuln in high or critical level

## How Has This Been Tested?
Create a PR in forked repo https://github.com/zdtsw/odh-dashboard/actions/runs/4799075808
Action was run and result can be download as artifacts

## Test Impact
N.A

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by shalberd** [comment]
Idia itself is very good, however, would this not be better-placed in odh-manifests? Dashboard image-reference is part of the recipes there, too.

**Comment by zdtsw** [comment]
> Idia itself is very good, however, would this not be better-placed in odh-manifests? Dashboard image-reference is part of the recipes there, too.

The reason I picked up dashboard than any other ODH repo is mostly based the language it uses.
And I would like to see how community feel about enable such tool.
My idea is to have it in as many repo as possible.
But on the other side, I am not sure it is better on the image level or on the source code level.
So the PR itself is more to open a conversation and discuss from here.

**Review by lucferbux — APPROVED** [review]
/lgtm

Although I would stale this until @zdtsw is back.

**Comment by lucferbux** [comment]
@zdtsw can you rebase main please? and before mergin, can we take a look, it seems that everything is ok but i would love to have more context

**Comment by zdtsw** [comment]
> @zdtsw can you rebase main please? and before mergin, can we take a look, it seems that everything is ok but i would love to have more context



> @zdtsw can you rebase main please? and before mergin, can we take a look, it seems that everything is ok but i would love to have more context

I did a rebase and now think it need approve to run Action https://github.com/opendatahub-io/odh-dashboard/actions/runs/5175998579
Also I added more context in the commit message. Let me know if anything not clear.

**Comment by lucferbux** [comment]
@zdtsw Running now, let's see!

**Comment by lucferbux** [comment]
Ok it seems to be working fine!

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by lucferbux** [comment]
@andrewballantyne everything seems ok here, should we merge it?

**Pull request merged**
