### PR TITLE
Move CONTRIBUTING to root

### LINKED ISSUE #461: [Feature Request]: Move CONTRIBUTING file to root
### Feature description

Right now, the CONTRIBUTING file is under `/docs` path. We should move that file into the root just to follow the standard structure of documenting a project. This might be a subtask of #195

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Fixes #461 

## How Has This Been Tested?

.

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by andrewballantyne — CHANGES_REQUESTED** [review]
We have links on our root README to this file. As well as one in the docs README.

Please update those links.

**Comment by lucferbux** [comment]
> We have links on our root README to this file. As well as one in the docs README.
> 
> Please update those links.

Right, forgot about that, updated.

**Comment by andrewballantyne** [comment]
And the `docs/README.md` too -- right? I'm not checking out your code but a quick search on whatever branch I am on says there is one there for `CONTRIBUTING.md`

**Comment by lucferbux** [comment]
> And the `docs/README.md` too -- right? I'm not checking out your code but a quick search on whatever branch I am on says there is one there for `CONTRIBUTING.md`

Yes, it's listed in the index page.

**Review by andrewballantyne — APPROVED** [review]
Looks good to me

**Pull request merged**
