### PR TITLE
Update 'Resource name' fields to meet UX guidelines: Image streams

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Towards [RHOAIENG-14746](https://issues.redhat.com/browse/RHOAIENG-14746)

## Description
Updates the create/edit dialog for Notebook Images to use the common `K8sNameDescriptionField` component in order to meet current UX guidelines.

### Create
image

### Create editing Resource name
image

### Edit
image

## How Has This Been Tested?
- Navigate to a `Settings` -> `Notebook images`
  - Select `Import new image
  - Enter an image location
  - Enter the name for the new notebook image
  - Enter a description for the new notebook image
  - View the resource name via the `Edit resource name` link.
  - Change the resource name to something invalid (ie. contains a space)
  - Verify the `Import` button is disabled
  - Change the resource name to something valid
  - Verify the `Import` button is enabled
  - Save the notebook image.
  - Verify the notebook is created with the correct Display name, Description, and Resource Name.
- Navigate to a `Settings` -> `Notebook images`
  - Select the kebab for an existing notebook image and choose `Edit`
  - Update the Name field
  - Notice the resource name is not editable
  - Update the description field
  - Save the notebook image
  - Verify the notebook image is updated with the correct Display name and Description.

## Test Impact
Updated unit tests for new fields

## Request review criteria:
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

/cc @simrandhaliw

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
This might resolve [RHOAIENG-13606](https://issues.redhat.com/browse/RHOAIENG-13606) as well. BTW, please check the comment I left in the ticket... The resource name regex check is different for ImageStream, not sure what's the best way to deal with that

**Review by DaoDaoNoCode — COMMENTED** [review]
Following above, try to import an image and put `--` in the resource k8s name, it could meet the requirements, but will throw an error. This won't happen to other resources (Notebooks, Projects, Secrets...).

Screenshot 2024-11-08 at 2 25 20 PM

**Comment by christianvogt** [comment]
K8s names are not all restricted to the same rules.
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names describes just some of those. Seems image streams is also different. We're going to need the regex and error message to be configurable.

**Comment by jeff-phillips-18** [comment]
@DaoDaoNoCode @christianvogt I have updated to include a specific regexp and message for imagestreams. Please see the updated image above.

I received the copy for the name specifications from  @kaedward

**Pull request merged**
