### PR TITLE
remove isAdmin logic for EnsureCompatiblePipelineServer empty state

### PR DESCRIPTION
**Pull request by Gkrumbach07**
closes: https://issues.redhat.com/browse/RHOAIENG-8635

## Description

removes the non admin state for incompatible pipeline version view

## How Has This Been Tested?

1. create a pipeline server and change its version to v1 (will need to manually update the DSPA yaml)
2. go to UI and go to this project with the v1 server
3. make sure you are a non odh admin user
4. should see a button to delete in the empty state error view

## Test Impact

updated tests for admin user to expect the button

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

No UI change, just logic

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Review by DaoDaoNoCode — COMMENTED** [review]
In this ticket description I am seeing "For consistency, the CTA should be shown on the page for all user types that **are capable of** deleting the pipeline server". I am wondering if this means we should change the detection of ODH admin to the project admin where the pipeline server is running?

**Comment by Gkrumbach07** [comment]
When i talked with UX, they said that if the user can delete the server, we should show it. which is basically anyone that can get to that page @DaoDaoNoCode

**Review by DaoDaoNoCode — APPROVED** [review]
/lgtm

**Pull request merged**
