### PR TITLE
Change pagination to compact style for all pipeline tables

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
JIRA: https://issues.redhat.com/browse/RHOAIENG-11428
(This should also fixes https://issues.redhat.com/browse/RHOAIENG-11383)

## Description

Change pagination to compact style at 3 tables.

Experiments table:

Screenshot 2024-09-09 at 5 54 48 PM

Pipeline schedules table:

Screenshot 2024-09-09 at 5 55 27 PM

Compare run ROC curve table:

Screenshot 2024-09-09 at 5 55 52 PM

This should cover all the tables in the pipeline area

## How Has This Been Tested?

Check all the pages in the pipelines and experiments area and make sure all the paginations are in the compact style.

## Test Impact

Modify the cypress tests because some paginations don't have the page number input anymore.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
Global pipelineTable should also be compact https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/pipelines/global/pipelines/PipelinesView.tsx

**Comment by Gkrumbach07** [comment]
@pnaik1 it looks like it is. you may be thinking of compact rows.

I tested it live and looks like all tables are compact pagination

/lgtm

**Comment by pnaik1** [comment]
oops yeah I  was thinking of row compact :(
Retested 
/lgtm

**Comment by YanshanSong** [comment]
niubi

**Pull request merged**
