### PR TITLE
set experimentalMemoryManagement=true for cypress

### PR DESCRIPTION
**Pull request by christianvogt**
cc @manosnoam 

## Description

Set `experimentalMemoryManagement=true` to enable support for improved memory management within Chromium-based browsers.
https://docs.cypress.io/guides/references/experiments#Configuration

> This feature helps prevent out-of-memory errors and improves test stability and performance by:
>  - Actively managing memory usage
>  - Clearing caches and performing garbage collection more aggressively

## How Has This Been Tested?

`npm run test:cypress-ci`

## Test Impact

N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by christianvogt** [comment]
cc @manosnoam

**Comment by manosnoam** [comment]
This improves our runtime in CI, when I pulled your PR:
image

**Review by manosnoam — COMMENTED** [review]
lgtm

**Review by mturley — APPROVED** [review]
Nice

**Pull request merged**
