### PR TITLE
Disable Model Metrics

### PR DESCRIPTION
**Pull request by andrewballantyne**
Closes: #998

## Description

Disable model metrics by using the hook to control if it's enabled or not and always set it to false.

## How Has This Been Tested?

- Model Serving Global Page => Model Table (link on the name)
- DS Projects => Model Serving Runtime Models => Model Table (link on the name)

Before
Screenshot 2023-03-09 at 3 57 50 PM
Screenshot 2023-03-09 at 3 58 07 PM

After
Screenshot 2023-03-09 at 3 59 00 PM
Screenshot 2023-03-09 at 3 59 17 PM

## Test Impact

Not to be tested at this time.

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by andrewballantyne** [comment]
cc @kywalker-rh / @vconzola / @jedemo

**Comment by andrewballantyne** [comment]
Cherrypicked to a branch `v2.7.0-fixes` of the tag `v2.7.0`. Will do a z-stream release shortly after this to indicate the removal of Model Metrics in ODH.

**Comment by vconzola** [comment]
LGTM.

**Comment by andrewballantyne** [comment]
Disabling for `main` and to-be `v2.8.0`

**Pull request merged**
