### PR TITLE
Fix docs and community link

### LINKED ISSUE #1534: [Bug]: Documentation link is broken
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

OpenDataHub core version (eg. `v1.6.0`)

### Version

1.7.0

### Current Behavior

Right now, the link to documentation is broken upstream, probably due to the refactoring of the odh webpage.

Screenshot 2023-07-18 at 16 02 21

### Expected Behavior

Navigating to the right documentation page.

### Steps To Reproduce

1. Click the question mark icon in the nav bar
2. Click "Documentation"

### Workaround (if any)

Remove the `.html` extension from the url.

### What browsers are you seeing the problem on?

_No response_

### Anything else

_No response_

### PR DESCRIPTION
**Pull request by manaswinidas**
Fixes #1534 

## Description

The `Documentation` and `Community` links were broken, just removed `.html` as described in #1534 

## How Has This Been Tested?

1. Click on the `Documentation` and `Community` links in top navbar (`?` icon)

## Test Impact

No tests needed(visual changes)

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by shalberd** [comment]
working fine, meaning, those are just the correct url, thank you :-)

@lucferbux what do you think?

**Comment by lucferbux** [comment]
> working fine, meaning, those are precisely the correct urls, thank you :-)
> 
> @lucferbux what do you think?

Yes, that's exactly it!

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by shalberd** [comment]
@lucferbux what do you think about the follow-up discussion at https://github.com/opendatahub-io/odh-dashboard/issues/1534#issuecomment-1655214880

separate ticket probably best?

**Comment by lucferbux** [comment]
> @lucferbux what do you think about the follow-up discussion at [#1534 (comment)](https://github.com/opendatahub-io/odh-dashboard/issues/1534#issuecomment-1655208613)
> separate ticket probably best?

I think andrew reply you back in the other thread. We currently have efforts to remove jupyterhub, so I think we are fine there, thanks for the heads up there too!

**Comment by shalberd** [comment]
@lucferbux yes, we're good. We can merge this PR, all questions solved and the links are correct.

**Comment by lucferbux** [comment]
@shalberd Perfect, I'll ping the team today in standup to get a second review and merge it asap.

**Comment by shalberd** [comment]
@lucferbux regarding other efforts to remove Jupyterhub, I have created a ticket https://github.com/opendatahub-io/odh-dashboard/issues/1616 but notice there is a WIP PR regarding that, where the question of what to put in the new jupyter quickstarts came up, I suggest taking know how and input from the people who work on the documentation website pages, like https://opendatahub.io/docs/getting-started-with-open-data-hub/#creating-a-data-science-project_get-started

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm

**Pull request merged**
