### PR TITLE
Support Truncated Model Serving Runtime Text Better

### PR DESCRIPTION
**Pull request by dpanshug**
Closes: #1861 

## Description
Added the <Truncate /> component within the Model Serving runtime to enhance text visibility and eliminate surplus content, ensuring a cleaner and more concise display.

## How Has This Been Tested?
1. Open settings < serving runtimes < Add serving runtime with long display-name.
2. Open a project and scroll below to "Models & model serving section"
3. Click on "Add server"
4. In dropdown of model serving, you can see long name being truncated.
5. After adding model serving, model serving name will also be truncated.

## Test Impact

Added integration testing in model serving, related "Add server" modal and creating storybook component for it.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

@vconzola

### CODE REVIEW

**Review by manaswinidas — COMMENTED** [review]
@dpanshug are you planning on adding any tests?

**Comment by dpanshug** [comment]
> @dpanshug are you planning on adding any tests?

Not sure about it, what sort of testing we can do here

**Comment by manaswinidas** [comment]
@dpanshug you can write tests for any part of model serving similar to what Pushpa will be doing with her PR. For reference: https://github.com/opendatahub-io/odh-dashboard/pull/1868#issuecomment-1737301016

**Comment by dpanshug** [comment]
Added integration testing in model serving.

**Review by manaswinidas — APPROVED** [review]
/lgtm

**Comment by christianvogt** [comment]
@vconzola please have a look at these changes

**Comment by vconzola** [comment]
LGTM

**Pull request merged**
