### PR TITLE
Auto-add issues to ODH Dashboard Planning Project

### LINKED ISSUE #1095: [Feature Request]:  Auto-add Issues to ODH Dashboard Planning Project
### Feature description

Add a Github workflow that automates the process of adding issues to Dashboard Planning Project

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by VaishnaviHire**
Closes #1095 

## Description
This workflow adds issues created in odh-dashboard to the [Dashboard Planning Project](https://github.com/orgs/opendatahub-io/projects/24/views/1). 

**Note** 
- This requires `GH_TOKEN` secret added to the repo. (GITHUB_TOKEN [cannot be used](https://github.com/actions/add-to-project/issues/264).)

## How Has This Been Tested?
- To test this, create an example issue in this test [repo](https://github.com/VaishnaviHire/test-workflows)
- This uses the same workflow to add issues to the sample project

## Request review criteria:

- [ ] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@VaishnaviHire how is this different than the current workflow that I have configured? 

image

**Comment by andrewballantyne** [comment]
> Hi @VaishnaviHire sorry if I'm wrong, but should be this added to the `odh-manifest` repo rather than here? If the goal is to add issues created in the odh-manifest project, shouldn't this action be triggered there?

I misunderstood -- deleted my message. I'm in agreement with Lucas -- I think this should be in the ODH Manifests repo.

**Comment by VaishnaviHire** [comment]
Hi @lucferbux @andrewballantyne I already have the workflow [PR](https://github.com/opendatahub-io/odh-manifests/pull/781) in odh-manifests. I opened this for Dashboard project, since I thought the issues are being added manually. My bad, I updated the PR info that created the confusion.

If this behavior has been already configured, I can close this PR.

**Comment by lucferbux** [comment]
Ah, ok, I'm sorry for the confusion, I should've guessed that 🤦‍♂️

Great, I think this is not needed of the dashboard, the project is configured to add all isues to the board, let @andrewballantyne confirm this.

**Comment by andrewballantyne** [comment]
Ah -- then my deleted message was relevant... haha, too funny.

Yes, we have this in our configuration. No need for this. Unless the configuration goes away, we should be fine without this action file.

**Pull request closed without merging**
