### PR TITLE
Pipeline cleanup

### PR DESCRIPTION
**Pull request by andrewballantyne**
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/1207

## Description

Misc changes for Pipelines.

I have manually confirmed the slight UI changes with Kyle.

## How Has This Been Tested?

Manually going through the ticket to test each area.

## Test Impact

Not applicable -- https://github.com/opendatahub-io/odh-dashboard/issues/1184

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
code looks good. going to test functionality quick

**Comment by Gkrumbach07** [comment]
This link is incorrect
https://github.com/andrewballantyne/odh-dashboard/blob/pipeline-cleanup/frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableExpandedRow.tsx#L57-L62

takes me here: `http://localhost:4010/pipeline/test-gages-pr/pipelineRun/create` which is a 404

**Comment by Gkrumbach07** [comment]
Might not be an issue, but is this supposed to say no content or should there be a empty state screen

image

**Review by Gkrumbach07 — COMMENTED** [review]
See comments for bugs found

**Comment by lucferbux** [comment]
Just did a quick rundown, code seems to be in place, I saw all @Gkrumbach07 findings, I'll re-review once those issues are addressed.

**Comment by andrewballantyne** [comment]
@Gkrumbach07 / @lucferbux Fixed the issues you saw and a few QE found too. 

Let me know if there is anything else you spot.

**Comment by Gkrumbach07** [comment]
fixes look good, but if the data connection is not valid, the pipeline server spins indefinitely

**Comment by andrewballantyne** [comment]
> fixes look good, but if the data connection is not valid, the pipeline server spins indefinitely

I've added it to the UX meeting -- are you waiting for a response to this before approving?

**Pull request merged**
