### PR TITLE
Add support for public routes in kserve

### PR DESCRIPTION
**Pull request by lucferbux**
Closes https://issues.redhat.com/browse/RHOAIENG-6651

## Description

Add support for public/private routes in kserve

Screenshot 2024-07-17 at 16 07 27
Screenshot 2024-07-17 at 16 07 14

## How Has This Been Tested?

1. Install ODH Operator 2.14 (needed for the changes in kserve controller)
2. Create a new project
3. Deploy a single model server without a public route
4. Check that the internal route points to the right service
5. Now edit the deployment and make it public
6. Check that you end up getting a url

## Test Impact

Added integration tests and unit test.

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [X] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by lucferbux** [comment]
@vconzola Just pinging you to let you know no UX changes were required, we implemented the same UI as modlemesh. (see screenshots)

**Comment by vconzola** [comment]
Thanks for the update @lucferbux. I'm a bit surprised to see there's no "copy to clipboard" icon on the Route URL in the popover. Isn't that part of the modelmesh UI?

**Comment by lucferbux** [comment]
> Thanks for the update @lucferbux. I'm a bit surprised to see there's no "copy to clipboard" icon on the Route URL in the popover. Isn't that part of the modelmesh UI?

Yeah, updated with ClipboardCopy, we never had those on the mockups, included it in the PR for KServe and ModelMesh.

Screenshot 2024-07-17 at 16 07 14

Screenshot 2024-07-17 at 16 07 27

**Review by gitdallas — APPROVED** [review]

**Pull request merged**
