### PR TITLE
Add character length limit to the description field on create run form

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
JIRA: https://issues.redhat.com/browse/RHOAIENG-11058

## Description

Added a helper text and a length limit to the text area of the description field on the create run/schedule page.

Screenshot 2024-08-21 at 12 10 01 PM

## How Has This Been Tested?

1. Go to the create run/schedule page
2. Check if the helper text "Cannot exceed 255 characters" is under the description field
3. Try to type in a long string, and you cannot type more when you reach the limit of 255 characters

## Test Impact

Added some cypress checks in the current test cases to make sure the input field character length is limited.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@yannnz Could you check the screenshot above?

**Comment by yannnz** [comment]
> @yannnz Could you check the screenshot above?

Hi Juntao, it looks good to me. Thanks

**Comment by ppadti** [comment]
tested locally, 
/lgtm

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
