### PR TITLE
Resource icon updates

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Closes [RHOAIENG-14747](https://issues.redhat.com/browse/RHOAIENG-14747)
Closes [RHOAIENG-12299](https://issues.redhat.com/browse/RHOAIENG-12299)

## Description
Update the icons for the various resources. Create icons for each resource icon to allow them to be sized and colored appropriately.

Update the icon usage as specified in this [spreadsheet](https://docs.google.com/spreadsheets/d/1ei9FD_t4lEUzMMSU1pwKdscfQ9EGz4SH593SAM975f0/edit?usp=sharing)

## How Has This Been Tested?
Navigate to the pages described in the [spreadsheet](https://docs.google.com/spreadsheets/d/1ei9FD_t4lEUzMMSU1pwKdscfQ9EGz4SH593SAM975f0/edit?usp=sharing)
Validate the resource icon for each page / component

## Test Impact
No impact to automated tests as these changes are purely visual.

## Screen shots
1
image

________
2
image

________
3
image

________
4
image

________
5
image

________
6
image

________
7
image

________
8
image

________
9
image

________
10
image

________
11
image

________
12
image

________
13
image

________
14
image

________
15
image

________
16
image

________
17
image

________
18
image

________
19
image

________
20
image

________
21
image

________
22
image

________
23
image

________
24
image

________
25
image

________
26
image

________
27
image

________
28
image

________
29
image

________
30
image

________
31
image

________
32
image

________
33
image

________
34
image

________
35
image

________
36
image

________
#### Updated Project Selector:

image

## Request review criteria:
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

/cc @tobiastal @simrandhaliw

### CODE REVIEW

**Comment by tobiastal** [comment]
Thanks, Jeff.
I reviewed and added some comments in a new column in the [spreadsheet](https://docs.google.com/spreadsheets/d/1ei9FD_t4lEUzMMSU1pwKdscfQ9EGz4SH593SAM975f0/edit?gid=0#gid=0) for specific rows.

**Comment by jeff-phillips-18** [comment]
@tobiastal I've updated per your comments in the spreadsheet and updated the screenshots above.

**Comment by tobiastal** [comment]
Thanks @jeff-phillips-18 , there's still a few updates needed- I added these in a new column(=Tal review for PR 4/12) in the [spreadsheet](https://docs.google.com/spreadsheets/d/1ei9FD_t4lEUzMMSU1pwKdscfQ9EGz4SH593SAM975f0/edit?gid=0#gid=0) for specific rows.

**Comment by jeff-phillips-18** [comment]
@tobiastal Thanks. I've fixed and updated the screenshots above.

**Review by tobiastal — APPROVED** [review]

**Pull request merged**
