### PR TITLE
Update dockerfile to use numeric user id

### PR DESCRIPTION
**Pull request by ppadti**
Closes: [RHOAIENG-8824](https://issues.redhat.com/browse/RHOAIENG-8824)

## Description
This PR aims to update the dockerfile to use numeric user id.

## How Has This Been Tested?
 -  `make build ` to build the image using podman
 -  `make push` to push the image to the `IMAGE_REPOSITORY` specified in `.env.local` file
 -  deploy the image and check the dashboard container image to have `UID` as 1001

## Test Impact
NA

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by jiridanek** [comment]
Wow, I can lgtm in dashboard? Surprising.

**Comment by mturley** [comment]
@jiridanek I think anyone in the org can `lgtm` here, both `lgtm` and the `approved` label are needed to merge.

**Comment by mturley** [comment]
@ppadti this is maybe too nitpicky, but just so it's less confusing when we look in the log - can you edit the PR title/description and maybe also the commit message here to say "Update dockerfile to use numeric user id"? The problem is that the id is non-numeric and we're switching to numeric. The title sounds like we're doing the opposite.

**Comment by jiridanek** [comment]
/summary Update dockerfile to use numeric user id

Can't update commit message, but pr title can be changed through bot

**Comment by jiridanek** [comment]
/retitle Update dockerfile to use numeric user id

**Comment by mturley** [comment]
I edited the PR description as well directly. I suppose it's probably fine to have the commit message stay as is, if anyone is confused they'll find the PR.

**Review by mturley — APPROVED** [review]

**Pull request merged**
