### PR TITLE
Add tensorflow as supported runtime of onnx ootb

### LINKED ISSUE #1292: [Feature Request]: Add support for tensorflow in onnx ootb models
### Feature description

We are supporting the `Tensorflow` runtime in onnx models.
We should add this runtime to our OOTB models.

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Closes #1292 

## How Has This Been Tested?

1. Deploy the updated ootb templates
2. Check that you can select tensorflow as supported runtime

## Test Impact

Not added testing, we might include this into the model serving testing too

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by lucferbux** [comment]
@andrewballantyne I think it can be approved, there's two lgtms already

**Comment by andrewballantyne** [comment]
> @andrewballantyne I think it can be approved, there's two lgtms already

Please don't wait on me for this. You guys work it out among yourselves, that's why the process exists. If you're all confident in a change, just manually add the label.

**Pull request merged**
