### PR TITLE
[RHOAIENG-4648] UX content updates

### PR DESCRIPTION
**Pull request by jpuzz0**
Closes: [RHOAIENG-4648](https://issues.redhat.com/browse/RHOAIENG-4648)

## Description
- Updated UX content based on [this doc](https://docs.google.com/document/d/11SquEHVcyMVtuejCZxgAnFoY43GagYjQBhbfaI17Pn0/edit#heading=h.494mjlxa7qlu) for Pipelines & Runs.
- Fixed an issue where values for run details node statuses were not being translated to to readable Sentence-case strings.

## How Has This Been Tested?
Since some component re-arranging was involved with the Create/Schedule run page, those contents were verified manually. Project & Experiment have yet to be combined into 1 section and Pipeline root was not made into its own section yet. Both these things will happen when the Experiments feature is released.

## How to test
Verify all items from referenced UX doc related to Pipelines & Runs visible to users for release 2.9.

**Create run sections**
image

**Schedule run sections**
image

(cc @yannnz)

## Test Impact
Existing tests should still work

## Request review criteria:
Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
OK retest doesn't work... 🤷‍♂️

**Comment by Gkrumbach07** [comment]
This looks good

/lgtm
/approve

**Pull request merged**
