### PR TITLE
Make pipeline input parameters more evident

### PR DESCRIPTION
**Pull request by manaswinidas**
Addresses #1301 

## Description

Refer to #1301 
Screenshot 2023-06-20 at 4 54 56 PM

## How Has This Been Tested?

Try to create run after going to Data Science Pipelines => Runs

## Request review criteria:

- [X] The commits have meaningful messages (squashes happen on merge by the bot).
- [X] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

### CODE REVIEW

**Comment by manaswinidas** [comment]
Not sure if we should be changing `PARAMS = 'run-section-params'` too

**Review by Gkrumbach07 — COMMENTED** [review]
The issue suggested that the solution should be a description with the current label.

> adding a descriptor to the current field of Parameters in the run creation page

@kywalker-rh if you could verify this

**Comment by lucferbux** [comment]
> Not sure if we should be changing `PARAMS = 'run-section-params'` too

That's just an enum, you can change it if you want some consistency but it's still legible.

**Review by Gkrumbach07 — APPROVED** [review]
LGTM

**Review by lucferbux — APPROVED** [review]
/lgtm

**Pull request merged**
