### PR TITLE
rename trusty flag to disableTrustyBiasMetrics

### PR DESCRIPTION
**Pull request by Gkrumbach07**
https://issues.redhat.com/browse/RHOAIENG-14126

## Description

renames trusty flag to disableTrustyBiasMetrics and removed logic in the resourceUtils that prevents RHOAI from using the feature flag

## How Has This Been Tested?

Make sure enable trusty is visible in the permissions tab

## Test Impact

no test impact

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by pnaik1** [comment]
I see the enable trusty is visible in the setting tab
/lgtm

Screenshot 2024-10-17 at 6 08 29 PM

**Comment by Gkrumbach07** [comment]
/hold

waiting for confirmation from backend that this feature is going GA

**Review by Gkrumbach07 — COMMENTED** [review]
/approve

**Pull request merged**
