### PR TITLE
Enable model registry feature by default

### PR DESCRIPTION
**Pull request by mturley**
Closes [RHOAIENG-12588](https://issues.redhat.com/browse/RHOAIENG-12588).
Should not be merged until all other Model Registry MVP dev issues are closed. At time of writing, these are the only issues remaining:
* https://issues.redhat.com/browse/RHOAIENG-13045
* https://issues.redhat.com/browse/RHOAIENG-10135

## Description

Changes the default value of the `disableModelRegistry` feature flag to false in anticipation of the Model Registry MVP tech preview release.

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by mturley** [comment]
/hold
Holding this until the other MVP issues are closed.

**Comment by YuliaKrimerman** [comment]
/ lgtm

**Review by YuliaKrimerman — APPROVED** [review]

**Review by manaswinidas — APPROVED** [review]
/lgtm

**Pull request merged**
