### PR TITLE
Fixes: Workbench not editable for a little while after it's stopped

### PR DESCRIPTION
**Pull request by alexcreasy**
* Closes: #1551 
## Description

* When stopping a workbench:  
  * the switch now waits for the pods to spin down before showing status "stopped". 
  * The edit button in the kebab is disabled until the new stopped status.

## How Has This Been Tested?

* Stop a running workbench
* Wait for the edit button in the kebab to not be disabled
* Make an update to your workbench, e.g. change the notebook image.
* Ensure you do not see the error message reported in the bug.

## Test Impact

None.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [x] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by lucferbux** [comment]
/hold

We are gonna wait for next sprint on this one.

**Comment by lucferbux** [comment]
If you can rebase this @alexcreasy I'll do a review later today!

**Comment by alexcreasy** [comment]
/hold

HOLD - due to ambiguity around what should be in the RHODS 1.32 release we're not merging anything until we have clarity.

**Comment by alexcreasy** [comment]
Rebased.

**Comment by christianvogt** [comment]
tested
/lgtm

**Pull request merged**
