### PR TITLE
UX updates for pipeline logs

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
JIRA: https://issues.redhat.com/browse/RHOAIENG-6582

## Description

Follow the mockup to do the following updates:
1. Update the alert text, add 2 links to allow users to view raw logs or download the current step in the alert

Screenshot 2024-10-03 at 12 04 19 PM

2. Add a mousedown event to capture the highlight and click the event in the log window and pause the logs as needed
3. Updated the tooltip and icon for pause/resume logs

Screenshot 2024-10-03 at 12 20 48 PM

Screenshot 2024-10-03 at 12 21 10 PM

4. Remove the log viewer footer

## How Has This Been Tested?

1. Check the JIRA comment, use the log-forever-pipeline and create a run
2. Check the node logs, and verify all the changes based on the [mockup](https://www.figma.com/proto/etbN0ccCcZR1qKCpJXQNAg/Pipeline-phase-2?page-id=12031%3A86470&node-id=12534-92933&node-type=frame&viewport=714%2C-1503%2C0.35&t=214XjsqaSYtM6ngc-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=12534%3A92933)

## Test Impact

N/A, mostly UX updates, and needs manual verification.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@yannnz Can you check the screenshots above?

**Comment by yannnz** [comment]
> @yannnz Can you check the screenshots above?

@DaoDaoNoCode, wonder what are the sizes of the pause and resume action button? It seems a bit smaller. 
For the second point of adding mousedown events, just double check if I understand it correctly: we already have the scroll to pause interaction, so we only need to add highlight to pause and click to pause the log viewer streaming in this ticket, right?

**Comment by DaoDaoNoCode** [comment]
Hi @yannnz, the icon is 14x14, which is the same size as the search icon
Screenshot 2024-10-09 at 9 40 25 AM
Screenshot 2024-10-09 at 9 40 54 AM
Screenshot 2024-10-09 at 9 41 13 AM

For the second point, what you said is correct.

**Review by dpanshug — COMMENTED** [review]
When i expand or un-expand the LogTabStatus the log scrolls to the start. I would expect it to be at the same position. wdyt @yannnz ?

https://github.com/user-attachments/assets/d8e58cb7-a08e-47d7-bbcc-8d27b7f30aa6

**Comment by dpanshug** [comment]
@DaoDaoNoCode regarding the pause/resume icon size, i agree with @yannnz that seems a bit smaller to me also. can we increase to `lg`? https://www.patternfly.org/components/icon#sizes

**Comment by DaoDaoNoCode** [comment]
@yannnz @dpanshug I updated the icon size to medium, does it look better?

Screenshot 2024-10-09 at 12 29 26 PM

Screenshot 2024-10-09 at 12 27 13 PM

**Comment by DaoDaoNoCode** [comment]
As for the issue you mentioned above @dpanshug, I think it's a known issue in the PF log viewer and a limitation there because everything got rendered dynamically. When the container height changes, it's hard to estimate which line it remained at.

**Review by Gkrumbach07 — APPROVED** [review]
/lgtm

tested and works as expected. I am able to highlight and copy without it jumping around

**Pull request merged**
